/* Max Martin discography data.
   Compiled from Wikipedia's "Max Martin production discography" and "Max Martin" articles,
   then cross-checked against ASCAP's public ACE/Songview repertory search (776 registered
   works under his three confirmed writer IPI numbers: 254380962 "Max Martin",
   215866753 "Sandberg Martin Karl", 293094253 "Martin Max" - all verified as the same
   person via shared co-writers/works, e.g. "A Little Bit Longer" with Denniz PoP).
   role: array of credit types ("Writer", "Producer", "Artist")
   collab: co-writers/co-producers (aliases normalized: Dag Volle -> Denniz PoP,
           Lukasz Gottwald -> Dr. Luke, Johan Schuster -> Shellback, Onika Maraj -> Nicki Minaj,
           Kesha Sebert -> Kesha) */
const MAX_MARTIN_SONGS = [
// ---- 1991 ----
{t:"Sommarnatt",a:"Camilla",y:1991,alb:"non-album single",role:["Writer"],collab:["David Garpenståhl","Alexander Kronlund"]},
// ---- 1993 ----
{t:"Pretend I'm God",a:"It's Alive",y:1993,alb:"Earthquake Visions",role:["Writer","Artist"],collab:["Per Aldeheim","Kim Björkegren","Anders Gustavsson","Peter Kahm","Johan Rosth"],trivia:"From the one album by It's Alive, the glam-metal band Max Martin fronted as singer 'Martin White' before he became a producer — years before Cheiron, this is him as a performing artist in his own right.",source:"https://en.wikipedia.org/wiki/It%27s_Alive_(band)"},
{t:"Sing This Blues",a:"It's Alive",y:1993,alb:"Earthquake Visions",role:["Writer","Artist"],collab:["Per Aldeheim","Kim Björkegren","Anders Gustavsson","Peter Kahm","Johan Rosth"]},
// ---- 1994 ----
{t:"Me No Want Miseria",a:"E-Type",y:1994,alb:"Made in Sweden",role:["Writer"],collab:["Martin Eriksson","Herbie Crichlow"]},
// ---- 1995 ----
{t:"Gotta Be You",a:"3T feat. Herbie",y:1995,alb:"Brotherhood",role:["Writer"],collab:["Denniz PoP","Herbie Crichlow"]},
{t:"Big Funky Dealer",a:"Herbie",y:1995,alb:"Fingers",role:["Writer"],collab:["Denniz PoP","Herbie Crichlow"]},
{t:"Change",a:"Herbie",y:1995,alb:"Fingers",role:["Writer"],collab:["Denniz PoP","Herbie Crichlow"]},
{t:"Come Together",a:"Herbie",y:1995,alb:"Fingers",role:["Writer"],collab:["Herbie Crichlow"]},
{t:"Gangs to the Max",a:"Herbie",y:1995,alb:"Fingers",role:["Writer"],collab:["Denniz PoP","Herbie Crichlow"]},
{t:"Rainbow Child",a:"Herbie",y:1995,alb:"Fingers",role:["Writer"],collab:["Denniz PoP","Herbie Crichlow"]},
{t:"Right Type of Mood",a:"Herbie",y:1995,alb:"Fingers",role:["Writer"],collab:["Herbie Crichlow"]},
{t:"Electric",a:"Leila K",y:1995,alb:"Manic Panic",role:["Writer"],collab:["Denniz PoP","Herbie Crichlow","Laila El Khalifi","Chris Barbosa","Ed Chisholm"]},
{t:"Straight Up Funk",a:"Discovery",y:1995,alb:"non-album single",role:["Writer"],collab:["Denniz PoP","Herbie Crichlow"]},
// ---- 1996 ----
{t:"I Wanna Be with You",a:"Backstreet Boys",y:1996,alb:"Backstreet Boys",role:["Writer"],collab:["Denniz PoP"]},
{t:"Quit Playing Games (with My Heart)",a:"Backstreet Boys",y:1996,alb:"Backstreet Boys",role:["Writer","Producer"],collab:["Herbie Crichlow"],peak:2,trivia:"Max Martin's breakout international smash — the song that first put Cheiron Studios on the American radar.",source:"https://en.wikipedia.org/wiki/Quit_Playing_Games_(with_My_Heart)"},
{t:"Nobody But You",a:"Backstreet Boys",y:1996,alb:"Backstreet Boys",role:["Writer"],collab:["Denniz PoP","Herbie Crichlow"]},
{t:"We've Got It Goin' On",a:"Backstreet Boys",y:1996,alb:"Backstreet Boys",role:["Writer"],peak:69,collab:["Denniz PoP","Herbie Crichlow"]},
{t:"Up 'n Down",a:"George",y:1996,alb:"All the Way",role:["Writer"],collab:["Denniz PoP","George Shahin","Marco Rakascan"]},
{t:"The Things You Do",a:"George",y:1996,alb:"All the Way",role:["Writer"],collab:["George Shahin","Herbie Crichlow"]},
{t:"Blacklisted",a:"Leila K",y:1996,alb:"Manic Panic",role:["Writer"],collab:["Denniz PoP","David Wahlgren"]},
{t:"C'Mon Now",a:"Leila K",y:1996,alb:"Manic Panic",role:["Writer"],collab:["Denniz PoP","Herbie Crichlow","Gene Simmons","Vincent Cusano"]},
{t:"Rude Boy",a:"Leila K",y:1996,alb:"Manic Panic",role:["Writer"],collab:["Denniz PoP","Herbie Crichlow","Laila El Khalifi","David Wahlgren"]},
// ---- 1997 ----
{t:"Everybody (Backstreet's Back)",a:"Backstreet Boys",y:1997,alb:"Backstreet's Back",role:["Writer","Producer"],peak:4,collab:["Denniz PoP"]},
{t:"As Long as You Love Me",a:"Backstreet Boys",y:1997,alb:"Backstreet's Back",role:["Writer","Producer"],collab:[]},
{t:"That's the Way I Like It",a:"Backstreet Boys",y:1997,alb:"Backstreet's Back",role:["Writer"],collab:["Denniz PoP","Herbie Crichlow"]},
{t:"10,000 Promises",a:"Backstreet Boys",y:1997,alb:"Backstreet's Back",role:["Writer"],collab:["DeDe"]},
{t:"Get to You",a:"DeDe",y:1997,alb:"I Do",role:["Writer"],collab:["Per Magnusson","David Kreuger","Kristian Lundin"]},
{t:"My Lover",a:"DeDe",y:1997,alb:"I Do",role:["Writer"],collab:["Per Magnusson","David Kreuger","DeDe Lopez"]},
{t:"Do You Know (What It Takes)",a:"Robyn",y:1997,alb:"Robyn Is Here",role:["Writer"],peak:7,collab:["Robyn","Denniz PoP","Herbie Crichlow"]},
{t:"Show Me Love",a:"Robyn",y:1997,alb:"Robyn Is Here",role:["Writer","Producer"],peak:7,collab:["Robyn"]},
{t:"I'll Be There for You",a:"Solid HarmoniE",y:1997,alb:"Solid HarmoniE",role:["Writer"],collab:["Kristian Lundin"]},
{t:"I Wanna Love You",a:"Solid HarmoniE",y:1997,alb:"Solid HarmoniE",role:["Writer"],collab:["Kristian Lundin"]},
{t:"I Want You to Want Me",a:"Solid HarmoniE",y:1997,alb:"Solid HarmoniE",role:["Writer"],collab:["Jacob \"Jake\" Schulze"]},
{t:"To Love Once Again",a:"Solid HarmoniE",y:1997,alb:"Solid HarmoniE",role:["Writer"],collab:["Kristian Lundin"]},
// ---- 1998 ----
{t:"It's the Things You Do",a:"5ive",y:1998,alb:"5ive",role:["Writer"],collab:["George Shahin","Herbie Crichlow"]},
{t:"Slam Dunk (Da Funk)",a:"5ive",y:1998,alb:"5ive",role:["Writer"],collab:["Denniz PoP","Jacob \"Jake\" Schulze","Herbie Crichlow"]},
{t:"Until the Time Is Through",a:"5ive",y:1998,alb:"5ive",role:["Writer"],collab:["Andreas Carlsson"]},
{t:"Don't You Want It",a:"5ive",y:1998,alb:"5ive",role:["Writer"],collab:["Denniz PoP","Richard Breen","Jason Brown","Sean Conlon","Ritchie Neville","Scott Robinson"]},
{t:"Before the Night Is Over",a:"Bryan Adams",y:1998,alb:"On a Day Like Today",role:["Writer"],collab:["Bryan Adams"]},
{t:"Cloud Number Nine",a:"Bryan Adams",y:1998,alb:"On a Day Like Today",role:["Writer"],collab:["Bryan Adams","Gretchen Peters"]},
{t:"Superhero / For All That You Want",a:"Gary Barlow",y:1998,alb:"Open Road",role:["Writer"],collab:["Kristian Lundin","Gary Barlow"]},
{t:"A Little Bit Longer",a:"Jessica Folcker",y:1998,alb:"Jessica",role:["Writer"],collab:["Denniz PoP"]},
{t:"Falling in Love",a:"Jessica Folcker",y:1998,alb:"Jessica",role:["Writer"],collab:["Andreas Carlsson"]},
{t:"How Will I Know (Who You Are)",a:"Jessica Folcker",y:1998,alb:"Jessica",role:["Writer"],collab:["Kristian Lundin","Andreas Carlsson"]},
{t:"Private Eye",a:"Jessica Folcker",y:1998,alb:"Jessica",role:["Writer"],collab:["Denniz PoP"]},
{t:"Tell Me What You Like",a:"Jessica Folcker",y:1998,alb:"Jessica",role:["Writer"],collab:["Denniz PoP","Herbie Crichlow"]},
{t:"Turned and Walked Away",a:"Jessica Folcker",y:1998,alb:"Jessica",role:["Writer"],collab:["Jacob \"Jake\" Schulze"]},
{t:"I Want You Back",a:"*NSYNC",y:1998,alb:"*NSYNC",role:["Writer"],peak:13,collab:["Denniz PoP"]},
{t:"Tearin' Up My Heart",a:"*NSYNC",y:1998,alb:"*NSYNC",role:["Writer"],peak:59,collab:["Kristian Lundin"]},
{t:"...Baby One More Time",a:"Britney Spears",y:1998,alb:"...Baby One More Time",role:["Writer","Producer"],collab:[],peak:1,trivia:"Written for TLC first — they turned it down, reportedly finding it 'too kiddie' and too Swedish-pop. Britney Spears recorded it instead and it became her signature song and one of the best-selling singles of all time.",source:"https://en.wikipedia.org/wiki/...Baby_One_More_Time"},
// ---- 1999 ----
{t:"Larger than Life",a:"Backstreet Boys",y:1999,alb:"Millennium",role:["Writer"],collab:["Kristian Lundin","Brian Littrell"],peak:25},
{t:"I Want It That Way",a:"Backstreet Boys",y:1999,alb:"Millennium",role:["Writer","Producer"],collab:["Andreas Carlsson"],peak:6,trivia:"Famous for lyrics that don't logically connect ('You are my fire, the one desire... but we are two worlds apart') — the melody was locked in before the words made full sense, a hallmark of Martin's melody-first ('melodic math') songwriting method.",source:"https://en.wikipedia.org/wiki/I_Want_It_That_Way"},
{t:"Show Me the Meaning of Being Lonely",a:"Backstreet Boys",y:1999,alb:"Millennium",role:["Writer"],peak:6,collab:["Herbie Crichlow"]},
{t:"It's Gotta Be You",a:"Backstreet Boys",y:1999,alb:"Millennium",role:["Writer"],collab:["Robert John \"Mutt\" Lange"]},
{t:"Don't Want You Back",a:"Backstreet Boys",y:1999,alb:"Millennium",role:["Writer","Producer"],collab:[]},
{t:"Don't Wanna Lose You Now",a:"Backstreet Boys",y:1999,alb:"Millennium",role:["Writer","Producer"],collab:[]},
{t:"The One",a:"Backstreet Boys",y:1999,alb:"Millennium",role:["Writer"],peak:30,collab:["Brian Littrell"]},
{t:"(You Drive Me) Crazy",a:"Britney Spears",y:1999,alb:"...Baby One More Time",role:["Writer"],collab:["Jörgen Elofsson","Per Magnusson","David Kreuger"],peak:10},
{t:"I Will Be There",a:"Britney Spears",y:1999,alb:"...Baby One More Time",role:["Writer"],collab:["Andreas Carlsson"]},
{t:"That's the Way It Is",a:"Celine Dion",y:1999,alb:"All the Way... A Decade of Song",role:["Writer"],peak:6,collab:["Kristian Lundin","Andreas Carlsson"]},
{t:"Right Through You",a:"Drain STH",y:1999,alb:"Freaks of Nature",role:["Writer"],collab:["Maria Sjöholm"]},
{t:"Simon Says",a:"Drain STH",y:1999,alb:"Freaks of Nature",role:["Writer"],collab:["Martina Axén","Maria Sjöholm","Herbie Crichlow"]},
{t:"For All That You Want",a:"Gary Barlow",y:1999,alb:"Twelve Months, Eleven Days",role:["Writer"],collab:["Gary Barlow","Kristian Lundin"]},
{t:"I Need You",a:"Westlife",y:1999,alb:"Westlife",role:["Writer"],collab:["Andreas Carlsson","Rami Yacoub"]},
// ---- 2000 ----
{t:"Tusen Röster",a:"Artister för Amnesty",y:2000,alb:"non-album single",role:["Writer"],collab:["Mauro Scocco"]},
{t:"The Call",a:"Backstreet Boys",y:2000,alb:"Black & Blue",role:["Writer"],peak:52,collab:["Rami Yacoub"]},
{t:"Shape of My Heart",a:"Backstreet Boys",y:2000,alb:"Black & Blue",role:["Writer"],peak:9,collab:["Rami Yacoub","Lisa Miskovsky"]},
{t:"Get Another Boyfriend",a:"Backstreet Boys",y:2000,alb:"Black & Blue",role:["Writer"],collab:["Rami Yacoub"]},
{t:"It's True",a:"Backstreet Boys",y:2000,alb:"Black & Blue",role:["Writer"],collab:["Andreas Carlsson","Kevin Richardson"]},
{t:"It's My Life",a:"Bon Jovi",y:2000,alb:"Crush",role:["Writer"],peak:33,collab:["Jon Bon Jovi","Richie Sambora"],trivia:"Max Martin's first major rock co-write outside the Cheiron pop machine — proof his melodic sensibility could cross genres. After writing it with Bon Jovi and Sambora, Martin brought it home to Cheiron and produced a demo of it with Rami Yacoub — but by their own account, the demo leaned so hard into their usual polished pop style that it just didn't land as a rock song, and Yacoub has said they were harshly unimpressed with it themselves. Bon Jovi reworked the track with producer Luke Ebbin for the released version, which is why Martin and Yacoub's production isn't what ended up on the record, even though Martin kept his co-writing credit.",source:"https://www.musicbusinessworldwide.com/to-this-day-i-dont-look-at-charts-i-dont-cloud-my-head-with-stuff-i-cant-affect/"},
{t:"Oops!... I Did It Again",a:"Britney Spears",y:2000,alb:"Oops!... I Did It Again",role:["Writer","Producer"],collab:["Rami Yacoub"],peak:9},
{t:"Stronger",a:"Britney Spears",y:2000,alb:"Oops!... I Did It Again",role:["Writer","Producer"],collab:["Rami Yacoub"],peak:11},
{t:"Don't Go Knocking on My Door",a:"Britney Spears",y:2000,alb:"Oops!... I Did It Again",role:["Writer"],collab:["Rami Yacoub","Alexander Kronlund","Jacob \"Jake\" Schulze"]},
{t:"Lucky",a:"Britney Spears",y:2000,alb:"Oops!... I Did It Again",role:["Writer"],collab:["Rami Yacoub","Alexander Kronlund"],peak:23},
{t:"Where Are You Now",a:"Britney Spears",y:2000,alb:"Oops!... I Did It Again",role:["Writer"],collab:["Rami Yacoub","Andreas Carlsson"]},
{t:"Can't Make You Love Me",a:"Britney Spears",y:2000,alb:"Oops!... I Did It Again",role:["Writer"],collab:["Kristian Lundin","Andreas Carlsson"]},
{t:"Girl in the Mirror",a:"Britney Spears",y:2000,alb:"Oops!... I Did It Again",role:["Writer"],collab:["Rami Yacoub","Jörgen Elofsson"]},
{t:"Missing You Crazy",a:"Jessica Folcker",y:2000,alb:"Dino",role:["Writer"],collab:["Jolyon Skinner"]},
{t:"It's Gonna Be Me",a:"*NSYNC",y:2000,alb:"No Strings Attached",role:["Writer"],peak:1,collab:["Rami Yacoub","Andreas Carlsson"]},
{t:"I'll Never Stop",a:"*NSYNC",y:2000,alb:"No Strings Attached",role:["Writer"],collab:["Kristian Lundin","Alexander Kronlund"]},
{t:"When You're Looking Like That",a:"Westlife",y:2000,alb:"Coast to Coast",role:["Writer"],collab:["Rami Yacoub","Andreas Carlsson"]},
{t:"You Make Me Feel",a:"Westlife",y:2000,alb:"Coast to Coast",role:["Writer"],collab:["Nick Jarl","Patric Jonsson"]},
// ---- 2001 ----
{t:"Bimbo",a:"Lambretta",y:2001,alb:"Lambretta",role:["Writer"],collab:["Per Aldeheim","Alexander Kronlund"]},
{t:"Creep",a:"Lambretta",y:2001,alb:"Lambretta",role:["Writer"],collab:["Per Aldeheim","Alexander Kronlund"]},
{t:"Tell Me, Tell Me...Baby",a:"*NSYNC",y:2001,alb:"Celebrity",role:["Writer"],collab:["Rami Yacoub"]},
{t:"I'm Stupid (Don't Worry 'Bout Me)",a:"Prime STH",y:2001,alb:"Underneath the Surface",role:["Writer"],collab:["Noa Modén"]},
{t:"Overprotected",a:"Britney Spears",y:2001,alb:"Britney",role:["Writer"],collab:["Rami Yacoub"],peak:86},
{t:"Bombastic Love",a:"Britney Spears",y:2001,alb:"Britney",role:["Writer"],collab:["Rami Yacoub"]},
{t:"Cinderella",a:"Britney Spears",y:2001,alb:"Britney",role:["Writer"],collab:["Rami Yacoub","Britney Spears"]},
{t:"I'm Not a Girl, Not Yet a Woman",a:"Britney Spears",y:2001,alb:"Britney",role:["Writer"],collab:["Rami Yacoub"]},
// ---- 2002 ----
{t:"Unbelievable",a:"Def Leppard",y:2002,alb:"X",role:["Writer"],collab:["Andreas Carlsson","Per Aldeheim"]},
{t:"Is It Love",a:"Play",y:2002,alb:"Play",role:["Writer"],collab:["Jörgen Elofsson"]},
{t:"Just Hate Me",a:"Pain",y:2002,alb:"Nothing Remains the Same",role:["Writer"],collab:["Per Aldeheim"]},
{t:"Only a Woman like You",a:"Michael Bolton",y:2002,alb:"Only a Woman like You",role:["Writer"],collab:["Robert John \"Mutt\" Lange","Shania Twain","Rami Yacoub"]},
{t:"I Got You",a:"Nick Carter",y:2002,alb:"Now or Never",role:["Writer"],collab:["Rami Yacoub"]},
{t:"Blow Your Mind",a:"Nick Carter",y:2002,alb:"Now or Never",role:["Writer"],collab:["Rami Yacoub","Per Aldeheim"]},
{t:"I Just Wanna Take You Home",a:"Nick Carter",y:2002,alb:"Now or Never",role:["Writer"],collab:["Rami Yacoub","Per Aldeheim"]},
// ---- 2003 ----
{t:"Love Is All We Need",a:"Celine Dion",y:2003,alb:"One Heart",role:["Writer"],collab:["Rami Yacoub"]},
{t:"Faith",a:"Celine Dion",y:2003,alb:"One Heart",role:["Writer"],collab:["Rami Yacoub"]},
{t:"In His Touch",a:"Celine Dion",y:2003,alb:"One Heart",role:["Writer"],collab:["Rami Yacoub"]},
// ---- 2004 ----
{t:"Don't Cry for Pain",a:"Ana Johnsson",y:2004,alb:"The Way I Am",role:["Writer"],collab:["Ana Johnsson"]},
{t:"I'm Stupid",a:"Ana Johnsson",y:2004,alb:"The Way I Am",role:["Writer"],collab:["Noa Modén"]},
{t:"Since U Been Gone",a:"Kelly Clarkson",y:2004,alb:"Breakaway",role:["Writer","Producer"],peak:2,collab:["Dr. Luke"],trivia:"Reportedly written and demoed very quickly with a rock edge Clarkson pushed for; it became a defining pop-rock crossover hit and a template for the Max Martin/Dr. Luke partnership.",source:"https://en.wikipedia.org/wiki/Since_U_Been_Gone"},
{t:"Behind These Hazel Eyes",a:"Kelly Clarkson",y:2004,alb:"Breakaway",role:["Writer"],peak:6,collab:["Kelly Clarkson","Dr. Luke"]},
{t:"Camilla",a:"E-Type",y:2004,alb:"Loud Pipes Save Lives",role:["Writer"],collab:["Fredrik Ekdahl","Martin Eriksson"]},
{t:"Olympia",a:"E-Type",y:2004,alb:"Loud Pipes Save Lives",role:["Writer"],collab:["Fredrik Ekdahl","Martin Eriksson"]},
// ---- 2005 ----
{t:"Analogue (All I Want)",a:"a-ha",y:2005,alb:"Analogue",role:["Writer"],collab:["Magne Furuholmen","Paul Waaktaar-Savoy"]},
{t:"Just Want You to Know",a:"Backstreet Boys",y:2005,alb:"Never Gone",role:["Writer"],peak:70,collab:["Dr. Luke"]},
{t:"I Still...",a:"Backstreet Boys",y:2005,alb:"Never Gone",role:["Writer"],collab:["Rami Yacoub"]},
{t:"Climbing the Walls",a:"Backstreet Boys",y:2005,alb:"Never Gone",role:["Writer"],collab:["Dr. Luke"]},
{t:"Siberia",a:"Backstreet Boys",y:2005,alb:"Never Gone",role:["Writer"],collab:["Rami Yacoub","Alexandra Talomaa"]},
{t:"Complicated",a:"Bon Jovi",y:2005,alb:"Have a Nice Day",role:["Writer"],collab:["Jon Bon Jovi","Billy Falcon"]},
{t:"Is It Love?",a:"Twill",y:2005,alb:"non-album single",role:["Writer"],collab:["Jörgen Elofsson"]},
{t:"Stand by Me",a:"Darin",y:2005,alb:"The Anthem",role:["Writer"],collab:["Alexandra Talomaa"]},
{t:"Break You",a:"Marion Raven",y:2005,alb:"Here I Am",role:["Writer"],collab:["Dr. Luke"]},
{t:"Here I Am",a:"Marion Raven",y:2005,alb:"Here I Am",role:["Writer"],collab:["Rami Yacoub","Marion Raven"]},
{t:"Little by Little",a:"Marion Raven",y:2005,alb:"Here I Am",role:["Writer"],collab:["Rami Yacoub","Peter Svensson","Marion Raven"]},
{t:"End of Me",a:"Marion Raven",y:2005,alb:"Here I Am",role:["Writer"],collab:["Rami Yacoub","Marion Raven"]},
{t:"Six Feet Under",a:"Marion Raven",y:2005,alb:"Here I Am",role:["Writer"],collab:["Rami Yacoub","Marion Raven"]},
{t:"Gotta Be Kidding",a:"Marion Raven",y:2005,alb:"Here I Am",role:["Writer"],collab:["Rami Yacoub","Camela Leierth","Marion Raven"]},
{t:"In Spite of Me",a:"Marion Raven",y:2005,alb:"Here I Am",role:["Writer"],collab:["Rami Yacoub","Alexandra Talomaa","Marion Raven"]},
{t:"There I Said It",a:"Marion Raven",y:2005,alb:"Here I Am",role:["Writer"],collab:["Marion Raven"]},
{t:"4ever",a:"The Veronicas",y:2005,alb:"The Secret Life Of...",role:["Writer"],collab:["Dr. Luke"]},
{t:"Everything I'm Not",a:"The Veronicas",y:2005,alb:"The Secret Life Of...",role:["Writer"],collab:["Dr. Luke","Jessica Origliasso","Lisa Origliasso","Rami Yacoub"]},
{t:"U Make Me Better",a:"Bo Bice",y:2005,alb:"The Real Thing",role:["Writer"],collab:["Dr. Luke","Jill Latiano"]},
{t:"Lie...It's All Right",a:"Bo Bice",y:2005,alb:"The Real Thing",role:["Writer"],collab:["Dr. Luke"]},
// ---- 2006 ----
{t:"Who Knew",a:"Pink",y:2006,alb:"I'm Not Dead",role:["Writer"],peak:9,collab:["Pink","Dr. Luke"]},
{t:"Cuz I Can",a:"Pink",y:2006,alb:"I'm Not Dead",role:["Writer"],collab:["Pink","Dr. Luke"]},
{t:"U + Ur Hand",a:"Pink",y:2006,alb:"I'm Not Dead",role:["Writer"],peak:9,collab:["Pink","Dr. Luke","Rami Yacoub"]},
{t:"Extraordinary Love",a:"Darin",y:2006,alb:"Break the News",role:["Writer"],collab:["Rami Yacoub","Robyn","Patrik Berger"]},
{t:"I'm Better",a:"Ashley Parker Angel",y:2006,alb:"Soundtrack to Your Life",role:["Writer"],collab:["Dr. Luke","Shelly Peiken"]},
{t:"Let U Go",a:"Ashley Parker Angel",y:2006,alb:"Soundtrack to Your Life",role:["Writer"],collab:["Dr. Luke"]},
{t:"Tap That",a:"Megan McCauley",y:2006,alb:"Better Than Blood",role:["Writer"],collab:["Dr. Luke","Megan McCauley"]},
{t:"Mistake",a:"Stephanie McIntosh",y:2006,alb:"Tightrope",role:["Writer"],collab:["Rami Yacoub","Arnthor Birgisson"]},
{t:"Pretty Rebels",a:"Linda Sundblad",y:2006,alb:"Oh My God!",role:["Writer"],collab:["Alexander Kronlund","Linda Sundblad","Tobias Karlsson"]},
{t:"I Don't Think So",a:"Kelis",y:2006,alb:"Kelis Was Here",role:["Writer"],collab:["Dr. Luke"]},
{t:"Hologram",a:"Tobias Regner",y:2006,alb:"Straight",role:["Writer"],collab:["Per Aldeheim","Tony Cornelissen"]},
// ---- 2007 ----
{t:"I Will Be",a:"Avril Lavigne",y:2007,alb:"The Best Damn Thing",role:["Writer"],collab:["Avril Lavigne","Dr. Luke"]},
{t:"Alone",a:"Avril Lavigne",y:2007,alb:"The Best Damn Thing",role:["Writer"],collab:["Avril Lavigne","Dr. Luke"]},
{t:"Alive",a:"Enrique Iglesias",y:2007,alb:"unreleased",role:["Writer"],collab:["Enrique Iglesias","Rami Yacoub","Arnthor Birgisson"]},
{t:"If That's OK with You",a:"Shayne Ward",y:2007,alb:"Breathless",role:["Writer"],collab:["Savan Kotecha","Arnthor Birgisson"]},
{t:"Carry You Home",a:"James Blunt",y:2007,alb:"All the Lost Souls",role:["Writer"],collab:["James Blunt"]},
{t:"Do It All",a:"Stanfour",y:2007,alb:"Wild Life",role:["Writer"],collab:["Per Aldeheim"]},
{t:"I Don't Care",a:"Apocalyptica",y:2007,alb:"Worlds Collide",role:["Writer"],collab:["Eicca Toppinen","Adam Gontier"]},
{t:"Stay My Baby",a:"Amy Diamond",y:2007,alb:"Music in Motion",role:["Writer"],collab:["Tommy Tysper"]},
{t:"Feels Like Tonight",a:"Daughtry",y:2007,alb:"Daughtry",role:["Writer"],collab:["Dr. Luke","Sheppard Solomon"]},
{t:"I Will Be",a:"Leona Lewis",y:2007,alb:"Spirit",role:["Writer"],peak:66,collab:["Avril Lavigne","Dr. Luke"]},
// ---- 2008 ----
{t:"I Kissed a Girl",a:"Katy Perry",y:2008,alb:"One of the Boys",role:["Writer","Producer"],collab:["Katy Perry","Dr. Luke","Cathy Dennis"],peak:1,trivia:"Katy Perry's breakout single; its bisexual-curiosity theme made it hugely controversial in 2008 while topping charts worldwide — the start of Max Martin's long run producing Perry's biggest hits.",source:"https://en.wikipedia.org/wiki/I_Kissed_a_Girl"},
{t:"Hot n Cold",a:"Katy Perry",y:2008,alb:"One of the Boys",role:["Writer"],collab:["Katy Perry","Dr. Luke"],peak:3},
{t:"Last Night",a:"Carolina Liar",y:2008,alb:"Coming to Terms",role:["Writer"],collab:["Tobias Karlsson","Chad Wolfinbarger"]},
{t:"Done Stealin'",a:"Carolina Liar",y:2008,alb:"Coming to Terms",role:["Writer"],collab:["Tobias Karlsson","Per Aldeheim","Chad Wolfinbarger"]},
{t:"Beautiful World",a:"Carolina Liar",y:2008,alb:"Coming to Terms",role:["Writer"],collab:["Tobias Karlsson","Chad Wolfinbarger"]},
{t:"Best Friend's Girl",a:"Carolina Liar",y:2008,alb:"Coming to Terms",role:["Writer"],collab:["Tobias Karlsson","Alexander Kronlund","Chad Wolfinbarger"]},
{t:"Generation",a:"Simple Plan",y:2008,alb:"Simple Plan",role:["Writer"],collab:["Simple Plan","Nate Hills","Arnold Lanni"]},
{t:"Watching Us Die Tonight",a:"Bullet for My Valentine",y:2008,alb:"Scream Aim Fire",role:["Writer"],collab:["Matt Tuck"]},
{t:"In Love with a Girl",a:"Gavin DeGraw",y:2008,alb:"Gavin DeGraw",role:["Writer"],collab:["Gavin DeGraw","Howard Benson"]},
{t:"Into the Nightlife",a:"Cyndi Lauper",y:2008,alb:"Bring Ya to the Brink",role:["Writer"],collab:["Cyndi Lauper","Peer Åström","Johan Bobäck"]},
{t:"I'm Gone I'm Going",a:"Lesley Roy",y:2008,alb:"Unbeautiful",role:["Writer"],collab:["Lesley Roy","Shellback","Alexander Kronlund"]},
{t:"Here for You Now",a:"Lesley Roy",y:2008,alb:"Unbeautiful",role:["Writer"],collab:["Lesley Roy"]},
{t:"Psycho Bitch",a:"Lesley Roy",y:2008,alb:"Unbeautiful",role:["Writer"],collab:["Lesley Roy","Savan Kotecha"]},
{t:"Slow Goodbye",a:"Lesley Roy",y:2008,alb:"Unbeautiful",role:["Writer"],collab:["Lesley Roy","Dr. Luke","Katy Perry"]},
{t:"Thinking Out Loud",a:"Lesley Roy",y:2008,alb:"Unbeautiful",role:["Writer"],collab:["Lesley Roy"]},
{t:"Dead But Breathing",a:"Lesley Roy",y:2008,alb:"Unbeautiful",role:["Writer"],collab:["Lesley Roy","Camela Leierth","Per Aldeheim"]},
{t:"Unbeautiful",a:"Lesley Roy",y:2008,alb:"Unbeautiful",role:["Writer"],collab:["Rami Yacoub","Lesley Roy"]},
{t:"Girl Like Me",a:"Skye Sweetnam",y:2008,alb:"Sound Soldier",role:["Writer"],collab:["Skye Sweetnam","Dr. Luke","Shelly Peiken"]},
{t:"So What",a:"Pink",y:2008,alb:"Funhouse",role:["Writer","Producer"],peak:1,collab:["Pink","Shellback"]},
{t:"I Don't Believe You",a:"Pink",y:2008,alb:"Funhouse",role:["Writer"],collab:["Pink"]},
{t:"Please Don't Leave Me",a:"Pink",y:2008,alb:"Funhouse",role:["Writer"],peak:17,collab:["Pink"]},
{t:"It's All Your Fault",a:"Pink",y:2008,alb:"Funhouse",role:["Writer"],collab:["Pink","Shellback"]},
{t:"Boring",a:"Pink",y:2008,alb:"Funhouse",role:["Writer"],collab:["Pink","Shellback"]},
{t:"Whataya Want from Me",a:"Pink",y:2008,alb:"Funhouse (unreleased Pink version)",role:["Writer"],collab:["Pink","Shellback"],trivia:"Pink recorded this first but shelved it; Adam Lambert released it in 2009 and it became one of his signature hits.",source:"https://en.wikipedia.org/wiki/Whataya_Want_from_Me"},
{t:"Identified",a:"Vanessa Hudgens",y:2008,alb:"Identified",role:["Writer"],collab:["Dr. Luke","Cathy Dennis"]},
{t:"Unbreakable Heart",a:"Sugababes",y:2008,alb:"Catfights and Spotlights",role:["Writer"],collab:["Klas Åhlund"]},
{t:"If U Seek Amy",a:"Britney Spears",y:2008,alb:"Circus",role:["Writer"],collab:["Shellback","Savan Kotecha","Alexander Kronlund"],peak:19,trivia:"Its title is a well-known phonetic wordplay on the sung hook, which drew radio and parental-advocacy pushback on release.",source:"https://en.wikipedia.org/wiki/If_U_Seek_Amy"},
// ---- 2009 ----
{t:"My Life Would Suck Without You",a:"Kelly Clarkson",y:2009,alb:"All I Ever Wanted",role:["Writer"],peak:1,collab:["Dr. Luke","Claude Kelly"]},
{t:"Hologram",a:"Dean",y:2009,alb:"Desire",role:["Writer"],collab:["Tony Cornelissen","Per Aldeheim"]},
{t:"Let It Rain",a:"Living Things",y:2009,alb:"Habeas Corpus",role:["Writer"],collab:["Cory Becker","Josh Rothman","Jason Rothman","Yves Rothman"]},
{t:"Oxygen",a:"Living Things",y:2009,alb:"Habeas Corpus",role:["Writer"],collab:["Shellback","Cory Becker","Josh Rothman","Jason Rothman","Yves Rothman"]},
{t:"Do It Up",a:"Mitchel Musso",y:2009,alb:"Mitchel Musso",role:["Writer"],collab:["Per Aldeheim"]},
{t:"3",a:"Britney Spears",y:2009,alb:"The Singles Collection",role:["Writer"],collab:["Shellback","Tiffany Amber"],peak:1},
{t:"Bigger",a:"Backstreet Boys",y:2009,alb:"This Is Us",role:["Writer"],collab:["Shellback","Tiffany Amber"]},
{t:"I Got You",a:"Leona Lewis",y:2009,alb:"Echo",role:["Writer"],collab:["Arnthor Birgisson","Savan Kotecha"]},
{t:"Outta My Head",a:"Leona Lewis",y:2009,alb:"Echo",role:["Writer"],collab:["Shellback","Savan Kotecha"]},
{t:"Quitter",a:"Carrie Underwood",y:2009,alb:"Play On",role:["Writer"],collab:["Shellback","Savan Kotecha"]},
{t:"Friday I'll Be Over U",a:"Allison Iraheta",y:2009,alb:"Just Like You",role:["Writer"],collab:["Shellback","Tiffany Amber","Savan Kotecha"]},
{t:"Just Like You",a:"Allison Iraheta",y:2009,alb:"Just Like You",role:["Writer"],collab:["Shellback","Savan Kotecha"]},
{t:"Whataya Want from Me",a:"Adam Lambert",y:2009,alb:"For Your Entertainment",role:["Writer"],peak:10,collab:["Pink","Shellback"]},
{t:"If I Had You",a:"Adam Lambert",y:2009,alb:"For Your Entertainment",role:["Writer"],peak:30,collab:["Shellback","Savan Kotecha"]},
{t:"Get It Over With",a:"Unsung Hero",y:2009,alb:"non-album single",role:["Writer"],collab:["Sofi Bonde","Tobias Karlsson"]},
{t:"Love Me to Pieces",a:"Erik Hassle",y:2009,alb:"Hassle",role:["Writer"],collab:["Erik Hassle","Tommy Tysper","Reinhold Mack"]},
// ---- 2010 ----
{t:"Kiss n Tell",a:"Kesha",y:2010,alb:"Animal",role:["Writer"],collab:["Kesha","Dr. Luke","Shellback"]},
{t:"Hungover",a:"Kesha",y:2010,alb:"Animal",role:["Writer"],collab:["Kesha","Shellback"]},
{t:"Dinosaur",a:"Kesha",y:2010,alb:"Animal",role:["Writer"],collab:["Kesha","Shellback"]},
{t:"Blow",a:"Kesha",y:2010,alb:"Cannibal",role:["Writer"],peak:7,collab:["Kesha","Dr. Luke","Benjamin Levin","Klas Åhlund","Allan Grigg"]},
{t:"Crazy Beautiful Life",a:"Kesha",y:2010,alb:"Cannibal",role:["Writer"],peak:93,collab:["Kesha","Dr. Luke","Pebe Sebert"]},
{t:"Grow a Pear",a:"Kesha",y:2010,alb:"Cannibal",role:["Writer"],collab:["Kesha","Dr. Luke","Benjamin Levin"]},
{t:"Oh Oh",a:"Miranda Cosgrove",y:2010,alb:"Sparks Fly",role:["Writer"],collab:["Peer Åström","Savan Kotecha"]},
{t:"In Spite of Me",a:"Erik Grönwall",y:2010,alb:"Somewhere Between a Rock and a Hard Place",role:["Writer"],collab:["Rami Yacoub","Alexandra Talomaa","Marion Raven"]},
{t:"California Gurls",a:"Katy Perry feat. Snoop Dogg",y:2010,alb:"Teenage Dream",role:["Writer","Producer"],collab:["Dr. Luke","Snoop Dogg","Katy Perry","Benjamin Levin","Bonnie McKee"]},
{t:"Teenage Dream",a:"Katy Perry",y:2010,alb:"Teenage Dream",role:["Writer","Producer"],collab:["Dr. Luke","Katy Perry","Benjamin Levin","Bonnie McKee"],peak:1},
{t:"Last Friday Night (T.G.I.F.)",a:"Katy Perry",y:2010,alb:"Teenage Dream",role:["Writer","Producer"],collab:["Dr. Luke","Bonnie McKee","Katy Perry"],peak:1},
{t:"The One That Got Away",a:"Katy Perry",y:2010,alb:"Teenage Dream",role:["Writer"],collab:["Dr. Luke","Katy Perry"],peak:3},
{t:"E.T.",a:"Katy Perry",y:2010,alb:"Teenage Dream",role:["Writer"],collab:["Dr. Luke","Joshua Coleman","Katy Perry"],peak:1},
{t:"Dynamite",a:"Taio Cruz",y:2010,alb:"Rokstarr",role:["Writer"],peak:2,collab:["Taio Cruz","Dr. Luke","Benjamin Levin","Bonnie McKee"]},
{t:"DJ Got Us Fallin' in Love",a:"Usher feat. Pitbull",y:2010,alb:"Versus",role:["Writer"],collab:["Shellback","Savan Kotecha","Pitbull"]},
{t:"Raise Your Glass",a:"Pink",y:2010,alb:"Greatest Hits... So Far!!!",role:["Writer","Producer"],peak:1,collab:["Pink","Shellback"]},
{t:"Fuckin' Perfect",a:"Pink",y:2010,alb:"Greatest Hits... So Far!!!",role:["Writer"],peak:2,collab:["Pink","Shellback"]},
{t:"Making Out",a:"Linda Sundblad",y:2010,alb:"Manifest",role:["Writer"],collab:["Linda Sundblad"]},
{t:"2 All My Girls",a:"Linda Sundblad",y:2010,alb:"Manifest",role:["Writer"],collab:["Linda Sundblad","Alexander Kronlund"]},
{t:"Time Machine",a:"Robyn",y:2010,alb:"Body Talk",role:["Writer"],collab:["Robyn","Shellback","Sophia Somajo"]},
{t:"Close to Close",a:"Shayne Ward",y:2010,alb:"Obsession",role:["Writer"],collab:["Arnthor Birgisson","Savan Kotecha"]},
// ---- 2011 ----
{t:"Hold It Against Me",a:"Britney Spears",y:2011,alb:"Femme Fatale",role:["Writer","Producer"],collab:["Dr. Luke","Bonnie McKee","Mathieu \"Billboard\" Jomphe-Lepine"],peak:1},
{t:"I Wanna Go",a:"Britney Spears",y:2011,alb:"Femme Fatale",role:["Writer"],collab:["Shellback","Savan Kotecha"],peak:7},
{t:"Till the World Ends",a:"Britney Spears",y:2011,alb:"Femme Fatale",role:["Writer"],collab:["Alexander Kronlund","Kesha","Dr. Luke"],peak:3},
{t:"Inside Out",a:"Britney Spears",y:2011,alb:"Femme Fatale",role:["Writer"],collab:["Dr. Luke","Mathieu \"Billboard\" Jomphe-Lepine"]},
{t:"Seal It With a Kiss",a:"Britney Spears",y:2011,alb:"Femme Fatale",role:["Writer"],collab:["Dr. Luke","Bonnie McKee","Henry Walter"]},
{t:"Criminal",a:"Britney Spears",y:2011,alb:"Femme Fatale",role:["Writer"],collab:["Shellback","Tiffany Amber"],peak:55},
{t:"Up n' Down",a:"Britney Spears",y:2011,alb:"Femme Fatale",role:["Writer"],collab:["Shellback","Savan Kotecha"]},
{t:"Dancing Crazy",a:"Miranda Cosgrove",y:2011,alb:"High Maintenance",role:["Writer"],collab:["Shellback","Avril Lavigne"]},
{t:"Breathe",a:"Fireal",y:2011,alb:"The Dark Side",role:["Writer"],collab:["Per Aldeheim","Tuomas Miettinen","Caleb Daniel Lit"]},
{t:"What the Hell",a:"Avril Lavigne",y:2011,alb:"Goodbye Lullaby",role:["Writer"],peak:11,collab:["Shellback","Avril Lavigne"]},
{t:"Wish You Were Here",a:"Avril Lavigne",y:2011,alb:"Goodbye Lullaby",role:["Writer"],peak:65,collab:["Shellback","Avril Lavigne"]},
{t:"Smile",a:"Avril Lavigne",y:2011,alb:"Goodbye Lullaby",role:["Writer"],peak:68,collab:["Shellback","Avril Lavigne"]},
{t:"I Love You",a:"Avril Lavigne",y:2011,alb:"Goodbye Lullaby",role:["Writer"],collab:["Shellback","Avril Lavigne"]},
{t:"Loser Like Me",a:"Glee Cast",y:2011,alb:"Glee: The Music, Volume 5",role:["Writer"],collab:["Adam Anders","Peer Åström","Savan Kotecha","Shellback"]},
{t:"Light Up the World",a:"Glee Cast",y:2011,alb:"Glee: The Music, Volume 6",role:["Writer"],collab:["Adam Anders","Peer Åström","Shellback","Savan Kotecha"]},
{t:"Can't Find Entrance",a:"Those Dancing Days",y:2011,alb:"Daydreams & Nightmares",role:["Writer"],collab:["Shellback","Cecilia Efraimsson","Marianne Evrell","Linnea Jonsson","Rebecka Rolfart","Lisa Wirström"]},
{t:"I'll Survive You",a:"BC Jean",y:2011,alb:"non-album single",role:["Writer"],collab:["Shellback","Savan Kotecha"]},
{t:"Hate Me",a:"BC Jean",y:2011,alb:"unreleased",role:["Writer"],collab:["Shellback","Britney Jean Carlson"]},
{t:"Come N Go",a:"Pitbull",y:2011,alb:"Planet Pit",role:["Writer"],collab:["Pitbull","Dr. Luke","Benjamin Levin","Enrique Iglesias"]},
{t:"With Ur Love",a:"Cher Lloyd",y:2011,alb:"Sticks + Stones",role:["Writer"],collab:["Shellback","Savan Kotecha"]},
{t:"Domino",a:"Jessie J",y:2011,alb:"Who You Are",role:["Writer"],peak:6,collab:["Dr. Luke","Claude Kelly","Jessie J","Henry Walter"]},
{t:"Cause I Am",a:"Cervello",y:2011,alb:"Cervello",role:["Writer"],collab:["Alexandra Talomaa","Pierre Stenson","Rickard Eriksson","Sigvard Järrebring","Gunnar Lilja"]},
// ---- 2012 ----
{t:"Part of Me",a:"Katy Perry",y:2012,alb:"Teenage Dream: The Complete Confection",role:["Writer","Producer"],collab:["Dr. Luke","Bonnie McKee","Katy Perry"],peak:1},
{t:"Wide Awake",a:"Katy Perry",y:2012,alb:"Teenage Dream: The Complete Confection",role:["Writer"],collab:["Katy Perry","Dr. Luke","Bonnie McKee","Henry Walter"],peak:2},
{t:"Va Va Voom",a:"Nicki Minaj",y:2012,alb:"Pink Friday: Roman Reloaded",role:["Writer"],peak:22,collab:["Nicki Minaj","Dr. Luke","Allan Grigg","Henry Walter"]},
{t:"Masquerade",a:"Nicki Minaj",y:2012,alb:"Pink Friday: Roman Reloaded",role:["Writer"],collab:["Nicki Minaj","Dr. Luke","Benjamin Levin","Henry Walter"]},
{t:"One More Night",a:"Maroon 5",y:2012,alb:"Overexposed",role:["Writer"],peak:1,collab:["Adam Levine","Shellback","Savan Kotecha"]},
{t:"Daylight",a:"Maroon 5",y:2012,alb:"Overexposed",role:["Writer"],peak:7,collab:["Adam Levine","Mason Levy","Sam Martin"]},
{t:"Scream",a:"Usher",y:2012,alb:"Looking 4 Myself",role:["Writer"],collab:["Shellback","Savan Kotecha","Usher"]},
{t:"Beauty and a Beat",a:"Justin Bieber feat. Nicki Minaj",y:2012,alb:"Believe",role:["Writer"],collab:["Savan Kotecha","Anton Zaslavski","Nicki Minaj"]},
{t:"This Is Love",a:"will.i.am feat. Eva Simons",y:2012,alb:"#willpower",role:["Writer"],collab:["Eva Simons","will.i.am","Steve Angello","Sebastian Ingrosso","Mike Hamilton"]},
{t:"Fast Car",a:"Taio Cruz",y:2012,alb:"TY.O",role:["Writer"],collab:["Taio Cruz","Klas Åhlund","Alexander Kronlund","Usher","Adam Baptiste"]},
{t:"Slut Like You",a:"Pink",y:2012,alb:"The Truth About Love",role:["Writer"],collab:["Pink","Shellback"]},
{t:"We Are Never Ever Getting Back Together",a:"Taylor Swift",y:2012,alb:"Red",role:["Writer","Producer"],peak:1,collab:["Taylor Swift","Shellback"],trivia:"Max Martin & Shellback's first collaboration with Taylor Swift — it became her first Billboard Hot 100 No. 1 and kicked off her pivot toward full pop production.",source:"https://en.wikipedia.org/wiki/We_Are_Never_Ever_Getting_Back_Together"},
{t:"22",a:"Taylor Swift",y:2012,alb:"Red",role:["Writer","Producer"],peak:20,collab:["Taylor Swift","Shellback"]},
{t:"I Knew You Were Trouble",a:"Taylor Swift",y:2012,alb:"Red",role:["Writer","Producer"],peak:2,collab:["Taylor Swift","Shellback"]},
{t:"Your Body",a:"Christina Aguilera",y:2012,alb:"Lotus",role:["Writer"],peak:34,collab:["Tiffany Amber","Savan Kotecha","Shellback"]},
{t:"Let There Be Love",a:"Christina Aguilera",y:2012,alb:"Lotus",role:["Writer"],collab:["Shellback","Savan Kotecha","Bonnie McKee","Oliver Goldstein","Oscar Holter","Jakke Erixson"]},
{t:"Tonight I'm Getting Over You",a:"Carly Rae Jepsen",y:2012,alb:"Kiss",role:["Writer"],collab:["Carly Rae Jepsen","Lukas Hilbert","Clarence Coffee Jr.","Shiloh Hoganson","Katerina \"Tryna\" Loules"]},
{t:"Warrior",a:"Kesha",y:2012,alb:"Warrior",role:["Writer"],collab:["Kesha","Pebe Sebert","Dr. Luke","Henry Walter"]},
{t:"C'Mon",a:"Kesha",y:2012,alb:"Warrior",role:["Writer"],peak:27,collab:["Kesha","Dr. Luke","Benjamin Levin","Bonnie McKee","Henry Walter"]},
{t:"Wherever You Are",a:"Kesha",y:2012,alb:"Warrior",role:["Writer"],collab:["Kesha","Dr. Luke","Henry Walter"]},
{t:"Only Wanna Dance with You",a:"Kesha",y:2012,alb:"Warrior",role:["Writer"],collab:["Kesha","Dr. Luke","Henry Walter"]},
{t:"Supernatural",a:"Kesha",y:2012,alb:"Warrior",role:["Writer"],collab:["Kesha","Dr. Luke","Benjamin Levin","Nik Kershaw","Henry Walter"]},
{t:"All That Matters (The Beautiful Life)",a:"Kesha",y:2012,alb:"Warrior",role:["Writer"],collab:["Kesha","Lukas Hilbert","Savan Kotecha","Alexander Kronlund","Shellback"]},
// ---- 2013 ----
{t:"Play It Again",a:"Becky G",y:2013,alb:"Play It Again EP",role:["Writer"],collab:["Becky G","Joshua Coleman","Dr. Luke","Niles Hollowell-Dhar","Henry Walter"]},
{t:"Can't Get Enough",a:"Becky G feat. Pitbull",y:2013,alb:"Play It Again EP",role:["Writer"],collab:["Becky G","Pitbull","Niles Hollowell-Dhar","Tzvetin Todorov","Gregor Salto","Dr. Luke","Urales Vargas","Henry Walter"]},
{t:"In a World Like This",a:"Backstreet Boys",y:2013,alb:"In a World Like This",role:["Writer"],collab:["Kristian Lundin","Savan Kotecha"]},
{t:"Easier to Lie",a:"Cassadee Pope",y:2013,alb:"Frame by Frame",role:["Writer"],collab:["Savan Kotecha","Shellback"]},
{t:"Nothing to Lose",a:"Emblem3",y:2013,alb:"Nothing to Lose",role:["Writer"],collab:["Johan Carlsson","Jacob Kasher Hindlin","Marco Borrero"]},
{t:"Vacation",a:"G.R.L.",y:2013,alb:"The Smurfs 2 soundtrack",role:["Writer"],collab:["Dr. Luke","Henry Walter","Bonnie McKee"]},
{t:"Roar",a:"Katy Perry",y:2013,alb:"Prism",role:["Writer","Producer"],collab:["Katy Perry","Dr. Luke","Bonnie McKee","Henry Walter"],peak:1,trivia:"Perry's empowerment anthem drew a plagiarism controversy for melodic similarity to Sara Bareilles' 'Brave', released the same year — both camps denied any copying.",source:"https://en.wikipedia.org/wiki/Roar_(song)"},
{t:"Legendary Lovers",a:"Katy Perry",y:2013,alb:"Prism",role:["Writer"],collab:["Katy Perry","Dr. Luke","Bonnie McKee","Henry Walter"]},
{t:"Birthday",a:"Katy Perry",y:2013,alb:"Prism",role:["Writer"],collab:["Katy Perry","Dr. Luke","Bonnie McKee","Henry Walter"],peak:17},
{t:"Walking on Air",a:"Katy Perry",y:2013,alb:"Prism",role:["Writer"],collab:["Katy Perry","Klas Åhlund","Camela Leierth","Adam Baptiste"],peak:34},
{t:"Unconditionally",a:"Katy Perry",y:2013,alb:"Prism",role:["Writer"],collab:["Katy Perry","Dr. Luke","Henry Walter"],peak:14},
{t:"Dark Horse",a:"Katy Perry feat. Juicy J",y:2013,alb:"Prism",role:["Writer","Producer"],collab:["Katy Perry","Juicy J","Dr. Luke","Sarah Hudson","Henry Walter"]},
{t:"This Is How We Do",a:"Katy Perry",y:2013,alb:"Prism",role:["Writer"],collab:["Katy Perry","Klas Åhlund"],peak:24},
{t:"International Smile",a:"Katy Perry",y:2013,alb:"Prism",role:["Writer"],collab:["Katy Perry","Dr. Luke","Henry Walter"]},
{t:"Ghost",a:"Katy Perry",y:2013,alb:"Prism",role:["Writer"],collab:["Katy Perry","Dr. Luke","Bonnie McKee","Henry Walter"]},
{t:"Love Me",a:"Katy Perry",y:2013,alb:"Prism",role:["Writer"],collab:["Katy Perry","Christian Karlsson","Vincent Pontare","Magnus Lidehäll"]},
// ---- 2014 ----
{t:"Dirty Love",a:"Cher Lloyd",y:2014,alb:"Sorry I'm Late",role:["Writer"],collab:["Cher Lloyd","Savan Kotecha","Shellback","Jakob Jerlström","Ludvig Söderberg"]},
{t:"Forever Until Tomorrow",a:"MKTO",y:2014,alb:"MKTO",role:["Writer"],collab:["Carl Falk","Rami Yacoub","Savan Kotecha","Emanuel Kiriakou","Evan Bogart"]},
{t:"Show Me What You Got",a:"G.R.L.",y:2014,alb:"G.R.L.",role:["Writer"],collab:["Dr. Luke","Henry Walter","Jacob Kasher Hindlin"]},
{t:"Rewind",a:"G.R.L.",y:2014,alb:"G.R.L.",role:["Writer"],collab:["Dr. Luke","Henry Walter","Ammar Malik","Jacob Kasher Hindlin"]},
{t:"Wild Wild Love",a:"Pitbull",y:2014,alb:"Globalization",role:["Writer"],peak:30,collab:["Dr. Luke","Henry Walter","Ammar Malik","Pitbull","Alexander Castillo Vasquez"]},
{t:"Dare (La La La)",a:"Shakira",y:2014,alb:"Shakira",role:["Writer"],collab:["Shakira","Dr. Luke","Mathieu \"Billboard\" Jomphe-Lepine","Henry Walter","Jay Singh","Raelene Arreguin","John J. Conte Jr."]},
{t:"Du Gamla Du Fria",a:"Zlatan feat. Day",y:2014,alb:"non-album single",role:["Writer"],collab:["Traditional","Joakim Jarl","Jimmy Koitzsch","Linus Eklöw"]},
{t:"Problem",a:"Ariana Grande feat. Iggy Azalea",y:2014,alb:"My Everything",role:["Writer"],collab:["Ilya Salmanzadeh","Iggy Azalea","Savan Kotecha"]},
{t:"Break Free",a:"Ariana Grande feat. Zedd",y:2014,alb:"My Everything",role:["Writer"],collab:["Savan Kotecha","Zedd"]},
{t:"Love Me Harder",a:"Ariana Grande & The Weeknd",y:2014,alb:"My Everything",role:["Writer"],collab:["Ahmad Balshe","Savan Kotecha","The Weeknd","Peter Svensson","Ali Payami"]},
{t:"Bang Bang",a:"Jessie J, Ariana Grande & Nicki Minaj",y:2014,alb:"My Everything / Sweet Talker",role:["Writer"],collab:["Rickard Göransson","Savan Kotecha","Nicki Minaj","Jessie J"]},
{t:"First Love",a:"Jennifer Lopez",y:2014,alb:"A.K.A.",role:["Writer"],collab:["Savan Kotecha","Ilya Salmanzadeh"]},
{t:"All My Friends",a:"Wrabel",y:2014,alb:"non-album single",role:["Writer"],collab:["Stephen Wrabel","Drew Pearson"]},
{t:"Blank Space",a:"Taylor Swift",y:2014,alb:"1989",role:["Writer","Producer"],peak:1,collab:["Taylor Swift","Shellback"],trivia:"Widely misheard lyric: 'got a long list of ex-lovers' is often heard as 'all the lonely Starbucks lovers' — Swift has joked about the mondegreen herself.",source:"https://en.wikipedia.org/wiki/Blank_Space"},
{t:"Style",a:"Taylor Swift",y:2014,alb:"1989",role:["Writer","Producer"],peak:6,collab:["Taylor Swift","Shellback","Ali Payami"]},
{t:"All You Had to Do Was Stay",a:"Taylor Swift",y:2014,alb:"1989",role:["Writer","Producer"],collab:["Taylor Swift","Shellback"]},
{t:"Shake It Off",a:"Taylor Swift",y:2014,alb:"1989",role:["Writer","Producer"],peak:1,collab:["Taylor Swift","Shellback"],trivia:"Was the subject of a years-long copyright lawsuit over the 'players gonna play, haters gonna hate' lyric; the suit was ultimately dismissed.",source:"https://en.wikipedia.org/wiki/Shake_It_Off"},
{t:"Bad Blood",a:"Taylor Swift",y:2014,alb:"1989",role:["Writer","Producer"],peak:1,collab:["Taylor Swift","Shellback"]},
{t:"Wildest Dreams",a:"Taylor Swift",y:2014,alb:"1989",role:["Writer","Producer"],peak:5,collab:["Taylor Swift","Shellback","Ali Payami"]},
{t:"How You Get the Girl",a:"Taylor Swift",y:2014,alb:"1989",role:["Writer","Producer"],collab:["Taylor Swift","Shellback"]},
{t:"Wonderland",a:"Taylor Swift",y:2014,alb:"1989 (Deluxe)",role:["Writer","Producer"],peak:51,collab:["Taylor Swift","Shellback"]},
{t:"New Romantics",a:"Taylor Swift",y:2014,alb:"1989 (Deluxe)",role:["Writer","Producer"],peak:46,collab:["Taylor Swift","Shellback"]},
// ---- 2015 ----
{t:"Can't Feel My Face",a:"The Weeknd",y:2015,alb:"Beauty Behind the Madness",role:["Writer","Producer"],peak:1,collab:["The Weeknd","Savan Kotecha","Ali Payami","Peter Svensson"],trivia:"A song about the numbing high of cocaine addiction, disguised as a euphoric Michael Jackson-style disco-pop love song — most listeners took years to notice the real subject.",source:"https://en.wikipedia.org/wiki/Can%27t_Feel_My_Face"},
{t:"In the Night",a:"The Weeknd",y:2015,alb:"Beauty Behind the Madness",role:["Writer","Producer"],peak:12,collab:["The Weeknd","Savan Kotecha","Ali Payami","Peter Svensson","Belly"]},
{t:"Nobody Love",a:"Tori Kelly",y:2015,alb:"Unbreakable Smile",role:["Writer"],collab:["Tori Kelly","Savan Kotecha","Carolina Liar"]},
{t:"California Lovers",a:"Tori Kelly feat. LL Cool J",y:2015,alb:"Unbreakable Smile",role:["Writer"],collab:["Tori Kelly","Savan Kotecha","Carolina Liar","Ali Payami","LL Cool J"]},
{t:"Falling Slow",a:"Tori Kelly",y:2015,alb:"Unbreakable Smile",role:["Writer"],collab:["Carolina Liar"]},
{t:"Back Together",a:"Robin Thicke feat. Nicki Minaj",y:2015,alb:"non-album single",role:["Writer"],collab:["Robin Thicke","Nicki Minaj","Savan Kotecha","Ali Payami"]},
{t:"Ghost Town",a:"Adam Lambert",y:2015,alb:"The Original High",role:["Writer"],peak:64,collab:["Adam Lambert","Sterling Fox","Ali Payami","Tobias Karlsson"]},
{t:"Another Lonely Night",a:"Adam Lambert",y:2015,alb:"The Original High",role:["Writer"],collab:["Adam Lambert","Sterling Fox","Ali Payami"]},
{t:"Around the World",a:"Natalie La Rose feat. Fetty Wap",y:2015,alb:"non-album single",role:["Writer"],collab:["Ilya Salmanzadeh","Savan Kotecha","Carolina Liar","Marco Borrero","DJ Frank E","Fetty Wap"]},
{t:"Cool for the Summer",a:"Demi Lovato",y:2015,alb:"Confident",role:["Writer"],collab:["Demi Lovato","Alexander Kronlund","Savan Kotecha","Ali Payami"]},
{t:"Confident",a:"Demi Lovato",y:2015,alb:"Confident",role:["Writer"],collab:["Demi Lovato","Ilya Salmanzadeh","Savan Kotecha"]},
{t:"Hands to Myself",a:"Selena Gomez",y:2015,alb:"Revival",role:["Writer"],collab:["Julia Michaels","Justin Tranter","Mattman & Robin","Selena Gomez"]},
{t:"On My Mind",a:"Ellie Goulding",y:2015,alb:"Delirium",role:["Writer"],peak:13,collab:["Ellie Goulding","Savan Kotecha","Ilya Salmanzadeh"]},
{t:"Codes",a:"Ellie Goulding",y:2015,alb:"Delirium",role:["Writer"],collab:["Ellie Goulding","Savan Kotecha","Ilya Salmanzadeh"]},
{t:"Love Me Like You Do",a:"Ellie Goulding",y:2015,alb:"Delirium / Fifty Shades of Grey soundtrack",role:["Writer"],peak:3,collab:["Savan Kotecha","Ilya Salmanzadeh","Ali Payami","Tove Lo"]},
{t:"Don't Need Nobody",a:"Ellie Goulding",y:2015,alb:"Delirium",role:["Writer"],collab:["Ellie Goulding","Savan Kotecha","Peter Svensson","Ludvig Söderberg","Jakob Jerlström"]},
{t:"Army",a:"Ellie Goulding",y:2015,alb:"Delirium",role:["Writer"],collab:["Ellie Goulding","Savan Kotecha","Ali Payami"]},
{t:"Lost and Found",a:"Ellie Goulding",y:2015,alb:"Delirium",role:["Writer"],collab:["Ellie Goulding","Laleh Pourkarim","Carl Falk","Joakim Berg"]},
{t:"Send My Love (To Your New Lover)",a:"Adele",y:2015,alb:"25",role:["Writer","Producer"],collab:["Adele","Shellback"]},
// ---- 2016 ----
{t:"Dangerous Woman",a:"Ariana Grande",y:2016,alb:"Dangerous Woman",role:["Writer"],peak:8,collab:["Carolina Liar","Ross Golan"]},
{t:"Into You",a:"Ariana Grande",y:2016,alb:"Dangerous Woman",role:["Writer","Producer"],peak:13,collab:["Ariana Grande","Savan Kotecha","Alexander Kronlund","Ilya Salmanzadeh"]},
{t:"Side to Side",a:"Ariana Grande feat. Nicki Minaj",y:2016,alb:"Dangerous Woman",role:["Writer"],collab:["Ariana Grande","Savan Kotecha","Alexander Kronlund","Nicki Minaj","Ilya Salmanzadeh"]},
{t:"Greedy",a:"Ariana Grande",y:2016,alb:"Dangerous Woman",role:["Writer"],collab:["Savan Kotecha","Alexander Kronlund","Ilya Salmanzadeh"]},
{t:"Sometimes",a:"Ariana Grande",y:2016,alb:"Dangerous Woman",role:["Writer"],collab:["Savan Kotecha","Peter Svensson","Ilya Salmanzadeh"]},
{t:"Bad Decisions",a:"Ariana Grande",y:2016,alb:"Dangerous Woman",role:["Writer"],collab:["Ariana Grande","Savan Kotecha","Ilya Salmanzadeh"]},
{t:"Touch It",a:"Ariana Grande",y:2016,alb:"Dangerous Woman",role:["Writer"],collab:["Savan Kotecha","Peter Svensson","Ali Payami"]},
{t:"Just Like Fire",a:"Pink",y:2016,alb:"Alice Through the Looking Glass soundtrack",role:["Writer"],peak:10,collab:["Pink","Shellback","Oscar Holter"]},
{t:"Can't Stop the Feeling!",a:"Justin Timberlake",y:2016,alb:"Trolls soundtrack",role:["Writer","Producer"],collab:["Justin Timberlake","Shellback"],trivia:"Earned Max Martin his first Academy Award nomination, for Best Original Song. It also became the first song to top the Hot 100 without any accompanying music video.",source:"https://en.wikipedia.org/wiki/Can%27t_Stop_the_Feeling!"},
{t:"Hair Up",a:"Justin Timberlake w/ Gwen Stefani, Ron Funches",y:2016,alb:"Trolls soundtrack",role:["Writer"],collab:["Justin Timberlake","Savan Kotecha","Shellback","Oscar Holter"]},
{t:"What U Workin' With?",a:"Justin Timberlake w/ Gwen Stefani",y:2016,alb:"Trolls soundtrack",role:["Writer"],collab:["Justin Timberlake","Savan Kotecha","Peter Svensson","Ilya Salmanzadeh"]},
{t:"Saw It Coming",a:"G-Eazy feat. Jeremih",y:2016,alb:"Ghostbusters soundtrack",role:["Writer"],collab:["Peter Svensson","Savan Kotecha","Ali Payami","G-Eazy","Ray Parker Jr."]},
{t:"Rise",a:"Katy Perry",y:2016,alb:"non-album single (Rio Olympics)",role:["Writer"],collab:["Katy Perry","Savan Kotecha","Ali Payami"]},
{t:"Never Been Hurt",a:"The Band Perry",y:2016,alb:"My Bad Imagination",role:["Writer"],collab:["Savan Kotecha","Carolina Liar","Kimberly Perry","Neil Perry","Reid Perry"]},
{t:"Rockin'",a:"The Weeknd",y:2016,alb:"Starboy",role:["Writer"],peak:44,collab:["The Weeknd","Peter Svensson","Savan Kotecha","Ali Payami","Belly"]},
{t:"Love to Lay",a:"The Weeknd",y:2016,alb:"Starboy",role:["Writer"],peak:71,collab:["The Weeknd","Peter Svensson","Savan Kotecha","Ali Payami","Belly"]},
{t:"A Lonely Night",a:"The Weeknd",y:2016,alb:"Starboy",role:["Writer"],peak:69,collab:["The Weeknd","Peter Svensson","Savan Kotecha","Ali Payami","Belly","Jason Quenneville"]},
{t:"Ordinary Life",a:"The Weeknd",y:2016,alb:"Starboy",role:["Writer"],peak:72,collab:["The Weeknd","Peter Svensson","Savan Kotecha","Ali Payami","Belly","Doc McKinney","Cirkut"]},
// ---- 2017 ----
{t:"Chained to the Rhythm",a:"Katy Perry feat. Skip Marley",y:2017,alb:"Witness",role:["Writer"],collab:["Katy Perry","Sia","Ali Payami","Skip Marley"]},
{t:"Bon Appétit",a:"Katy Perry feat. Migos",y:2017,alb:"Witness",role:["Writer"],collab:["Katy Perry","Migos","Shellback","Oscar Holter","Ferras"]},
{t:"Witness",a:"Katy Perry",y:2017,alb:"Witness",role:["Writer"],collab:["Katy Perry","Savan Kotecha","Ali Payami"]},
{t:"Hey Hey Hey",a:"Katy Perry",y:2017,alb:"Witness",role:["Writer"],collab:["Katy Perry","Sia","Ali Payami","Sarah Hudson"]},
{t:"Roulette",a:"Katy Perry",y:2017,alb:"Witness",role:["Writer"],collab:["Katy Perry","Ali Payami","Shellback","Ferras"]},
{t:"Lust for Life",a:"Lana Del Rey feat. The Weeknd",y:2017,alb:"Lust for Life",role:["Writer"],collab:["Lana Del Rey","Rick Nowels","The Weeknd"]},
{t:"...Ready for It?",a:"Taylor Swift",y:2017,alb:"Reputation",role:["Writer","Producer"],peak:4,collab:["Taylor Swift","Shellback","Ali Payami"]},
{t:"End Game",a:"Taylor Swift feat. Ed Sheeran & Future",y:2017,alb:"Reputation",role:["Writer"],collab:["Taylor Swift","Ed Sheeran","Shellback","Future"]},
{t:"I Did Something Bad",a:"Taylor Swift",y:2017,alb:"Reputation",role:["Writer","Producer"],collab:["Taylor Swift","Shellback"]},
{t:"Don't Blame Me",a:"Taylor Swift",y:2017,alb:"Reputation",role:["Writer","Producer"],collab:["Taylor Swift","Shellback"]},
{t:"Delicate",a:"Taylor Swift",y:2017,alb:"Reputation",role:["Writer","Producer"],peak:12,collab:["Taylor Swift","Shellback"]},
{t:"So It Goes...",a:"Taylor Swift",y:2017,alb:"Reputation",role:["Writer","Producer"],collab:["Taylor Swift","Shellback","Oscar Görres"]},
{t:"Gorgeous",a:"Taylor Swift",y:2017,alb:"Reputation",role:["Writer","Producer"],peak:13,collab:["Taylor Swift","Shellback"]},
{t:"King of My Heart",a:"Taylor Swift",y:2017,alb:"Reputation",role:["Writer","Producer"],collab:["Taylor Swift","Shellback"]},
{t:"Dancing with Our Hands Tied",a:"Taylor Swift",y:2017,alb:"Reputation",role:["Writer","Producer"],collab:["Taylor Swift","Shellback","Oscar Holter"]},
{t:"Revenge",a:"Pink feat. Eminem",y:2017,alb:"Beautiful Trauma",role:["Writer"],collab:["Pink","Eminem","Shellback"]},
{t:"Whatever You Want",a:"Pink",y:2017,alb:"Beautiful Trauma",role:["Writer"],collab:["Pink","Shellback"]},
{t:"For Now",a:"Pink",y:2017,alb:"Beautiful Trauma",role:["Writer"],collab:["Pink","Julia Michaels","Mattman & Robin"]},
{t:"Secrets",a:"Pink",y:2017,alb:"Beautiful Trauma",role:["Writer"],collab:["Pink","Shellback","Oscar Holter"]},
{t:"Naked",a:"James Arthur",y:2017,alb:"You",role:["Writer"],collab:["James Arthur","Carolina Liar","Savan Kotecha"]},
// ---- 2018 ----
{t:"We Are...",a:"Noah Cyrus feat. MØ",y:2018,alb:"non-album single",role:["Writer"],collab:["Noah Cyrus","Savan Kotecha","Ali Payami"]},
{t:"2002",a:"Anne-Marie",y:2018,alb:"Speak Your Mind",role:["Writer"],collab:["Ed Sheeran","Kristian Lundin"]},
{t:"No Tears Left to Cry",a:"Ariana Grande",y:2018,alb:"Sweetener",role:["Writer"],peak:3,collab:["Ariana Grande","Savan Kotecha","Ilya Salmanzadeh"]},
{t:"God Is a Woman",a:"Ariana Grande",y:2018,alb:"Sweetener",role:["Writer"],peak:8,collab:["Ariana Grande","Savan Kotecha","Ilya Salmanzadeh","Carolina Liar"]},
{t:"Everytime",a:"Ariana Grande",y:2018,alb:"Sweetener",role:["Writer"],peak:62,collab:["Ariana Grande","Savan Kotecha","Ilya Salmanzadeh"]},
{t:"No More",a:"PrettyMuch feat. French Montana",y:2018,alb:"PrettyMuch So Far...",role:["Writer"],collab:["Ludvig Söderberg","Oscar Görres","Peter Svensson","Savan Kotecha","French Montana"]},
// ---- 2019 ----
{t:"Bloodline",a:"Ariana Grande",y:2019,alb:"Thank U, Next",role:["Writer"],peak:22,collab:["Ariana Grande","Savan Kotecha","Ilya Salmanzadeh"]},
{t:"Bad Idea",a:"Ariana Grande",y:2019,alb:"Thank U, Next",role:["Writer"],peak:27,collab:["Ariana Grande","Savan Kotecha","Ilya Salmanzadeh"]},
{t:"Ghostin",a:"Ariana Grande",y:2019,alb:"Thank U, Next",role:["Writer"],peak:25,collab:["Ariana Grande","Victoria Monét","Savan Kotecha","Ilya Salmanzadeh"]},
{t:"Break Up with Your Girlfriend, I'm Bored",a:"Ariana Grande",y:2019,alb:"Thank U, Next",role:["Writer"],peak:2,collab:["Ariana Grande","Savan Kotecha","Ilya Salmanzadeh","Kevin Briggs","Kandi Burruss"]},
{t:"(Hey Why) Miss You Sometime",a:"Pink",y:2019,alb:"Hurts 2B Human",role:["Writer"],collab:["Shellback"]},
{t:"Finished What We Started",a:"Zac Brown Band feat. Brandi Carlile",y:2019,alb:"The Owl",role:["Writer"],collab:["Zac Brown","Johan Carlsson","Peter Svensson","Savan Kotecha"]},
{t:"I Don't Care",a:"Ed Sheeran & Justin Bieber",y:2019,alb:"No.6 Collaborations Project",role:["Writer"],collab:["Ed Sheeran","Fred again..","Poo Bear","Justin Bieber","Shellback"]},
{t:"Beautiful People",a:"Ed Sheeran feat. Khalid",y:2019,alb:"No.6 Collaborations Project",role:["Writer"],collab:["Ed Sheeran","Khalid","Fred again..","Shellback"]},
{t:"Remember the Name",a:"Ed Sheeran feat. Eminem & 50 Cent",y:2019,alb:"No.6 Collaborations Project",role:["Writer"],collab:["Ed Sheeran","Eminem","50 Cent","Organized Noize"]},
{t:"Take Me Back to London",a:"Ed Sheeran feat. Stormzy",y:2019,alb:"No.6 Collaborations Project",role:["Writer"],collab:["Ed Sheeran","Fred again..","Shellback","Stormzy"]},
{t:"How Do You Sleep?",a:"Sam Smith",y:2019,alb:"Love Goes",role:["Writer"],collab:["Sam Smith","Ilya Salmanzadeh","Savan Kotecha"]},
{t:"Motivation",a:"Normani",y:2019,alb:"non-album single",role:["Writer"],collab:["Normani","Ariana Grande","Ilya Salmanzadeh","Savan Kotecha"]},
{t:"Don't Call Me Angel",a:"Ariana Grande, Miley Cyrus & Lana Del Rey",y:2019,alb:"Charlie's Angels soundtrack",role:["Writer"],collab:["Ilya Salmanzadeh","Savan Kotecha","Alma"]},
{t:"Bad to You",a:"Ariana Grande feat. Normani & Nicki Minaj",y:2019,alb:"Charlie's Angels soundtrack",role:["Writer"],collab:["Ilya Salmanzadeh","Savan Kotecha","Nicki Minaj","Brandon Hollemon"]},
{t:"Nobody",a:"Ariana Grande w/ Chaka Khan",y:2019,alb:"Charlie's Angels soundtrack",role:["Writer"],collab:["Ilya Salmanzadeh","Savan Kotecha"]},
{t:"How I Look on You",a:"Ariana Grande",y:2019,alb:"Charlie's Angels soundtrack",role:["Writer"],collab:["Ilya Salmanzadeh","Savan Kotecha"]},
{t:"One More Try",a:"Jessie J",y:2019,alb:"& Juliet (musical)",role:["Writer"],collab:["Ilya Salmanzadeh","Savan Kotecha","David West Read","Oscar Holter","Peter Svensson"],trivia:"& Juliet, the West End/Broadway jukebox musical built almost entirely from Max Martin's songbook, opened in 2019 and turned decades of his pop hits into a Shakespeare-remix stage show.",source:"https://en.wikipedia.org/wiki/%26_Juliet"},
{t:"Mateo",a:"Tove Lo",y:2019,alb:"Sunshine Kitty",role:["Writer"],collab:["Tove Lo","Ludvig Söderberg","Jakob Jerlström"]},
{t:"Equally Lost",a:"Tove Lo feat. Doja Cat",y:2019,alb:"Sunshine Kitty",role:["Writer"],collab:["Tove Lo","Mattman & Robin","Doja Cat"]},
// ---- 2020 ----
{t:"The Other Side",a:"Justin Timberlake & SZA",y:2020,alb:"Trolls World Tour soundtrack",role:["Writer"],collab:["Justin Timberlake","Ludwig Göransson","Sarah Aarons","SZA"]},
{t:"Just Sing",a:"Justin Timberlake, Anna Kendrick, Kelly Clarkson",y:2020,alb:"Trolls World Tour soundtrack",role:["Writer"],collab:["Justin Timberlake","Ludwig Göransson","Sarah Aarons"]},
{t:"Hardest to Love",a:"The Weeknd",y:2020,alb:"After Hours",role:["Writer","Producer"],peak:25,collab:["Oscar Holter"]},
{t:"Scared to Live",a:"The Weeknd",y:2020,alb:"After Hours",role:["Writer"],peak:24,collab:["Oscar Holter","Belly","Daniel Lopatin","Elton John","Bernie Taupin"]},
{t:"Blinding Lights",a:"The Weeknd",y:2020,alb:"After Hours",role:["Writer","Producer"],peak:1,collab:["Oscar Holter","Belly","Jason Quenneville"],trivia:"Named Billboard's all-time #1 Hot 100 song in its 2021 60th-anniversary ranking, and spent a record-breaking 90 weeks on the chart. Its retro synth sound was directly inspired by 1980s acts like a-ha and Phil Collins.",source:"https://en.wikipedia.org/wiki/Blinding_Lights"},
{t:"In Your Eyes",a:"The Weeknd",y:2020,alb:"After Hours",role:["Writer"],peak:16,collab:["Oscar Holter","Belly"]},
{t:"Save Your Tears",a:"The Weeknd w/ Ariana Grande",y:2020,alb:"After Hours",role:["Writer","Producer"],collab:["Oscar Holter","Belly","Jason Quenneville"]},
{t:"Stupid Love",a:"Lady Gaga",y:2020,alb:"Chromatica",role:["Writer"],collab:["Lady Gaga","BloodPop","Tchami","Ely Rise"]},
// ---- 2021 ----
{t:"Stick with You",a:"Zara Larsson",y:2021,alb:"Poster Girl",role:["Writer"],collab:["Zara Larsson","Savan Kotecha","Ludvig Söderberg","Jakob Jerlström","Max Wolfgang"]},
{t:"Higher Power",a:"Coldplay",y:2021,alb:"Music of the Spheres",role:["Writer"],peak:53,collab:["Chris Martin","Guy Berryman","Jonny Buckland","Will Champion","Denise Carite","Federico Vindver"]},
{t:"Coloratura",a:"Coldplay",y:2021,alb:"Music of the Spheres",role:["Writer"],collab:["Coldplay","John Metcalfe","Davide Rossi"]},
{t:"My Universe",a:"Coldplay & BTS",y:2021,alb:"Music of the Spheres",role:["Writer"],collab:["Coldplay","Oscar Holter","BTS"],trivia:"Coldplay's collaboration with BTS gave Max Martin his first co-write on a K-pop crossover chart-topper, hitting #1 on the Billboard Hot 100.",source:"https://en.wikipedia.org/wiki/My_Universe"},
{t:"Music of the Spheres",a:"Coldplay",y:2021,alb:"Music of the Spheres",role:["Writer"],collab:["Coldplay","Daniel Green","Rik Simpson","Federico Vindver","Bill Rahko"]},
{t:"Humankind",a:"Coldplay",y:2021,alb:"Music of the Spheres",role:["Writer"],collab:["Coldplay","Jon Hopkins","Stephen Fry","Daniel Green","Federico Vindver","Oscar Holter"]},
{t:"Alien Choir",a:"Coldplay",y:2021,alb:"Music of the Spheres",role:["Writer"],collab:["Jon Hopkins"]},
{t:"Let Somebody Go",a:"Coldplay w/ Selena Gomez",y:2021,alb:"Music of the Spheres",role:["Writer"],collab:["Coldplay","Apple Martin","Livvi Franc","Oscar Holter","Bill Rahko","Metro Boomin"]},
{t:"Human Heart",a:"Coldplay w/ We Are King, Jacob Collier",y:2021,alb:"Music of the Spheres",role:["Writer"],collab:["Coldplay","We Are King","Jacob Collier"]},
{t:"People of the Pride",a:"Coldplay",y:2021,alb:"Music of the Spheres",role:["Writer"],collab:["Coldplay","Jesse Rogg","Sam Sparro","Derek Dixie","Bill Rahko"]},
{t:"Biutyful",a:"Coldplay",y:2021,alb:"Music of the Spheres",role:["Writer"],collab:["Coldplay","Oscar Holter","Davide Rossi"]},
{t:"Music of the Spheres II",a:"Coldplay",y:2021,alb:"Music of the Spheres",role:["Writer"],collab:["Coldplay"]},
{t:"Infinity Sign",a:"Coldplay",y:2021,alb:"Music of the Spheres",role:["Writer"],collab:["Coldplay","Jon Hopkins"]},
{t:"Beautiful",a:"Anne-Marie",y:2021,alb:"Therapy",role:["Writer"],collab:["Ed Sheeran","Elvira Anderfjärd"]},
{t:"Who's in Your Head",a:"Jonas Brothers",y:2021,alb:"non-album single",role:["Writer"],collab:["Jonas Brothers","Ilya Salmanzadeh","Rami Yacoub","David Stewart"]},
{t:"Wildest Dreams (Taylor's Version)",a:"Taylor Swift",y:2021,alb:"1989 (Taylor's Version)",role:["Writer","Producer"],peak:19,collab:["Taylor Swift","Shellback"]},
{t:"I Knew You Were Trouble (Taylor's Version)",a:"Taylor Swift",y:2021,alb:"Red (Taylor's Version)",role:["Writer","Producer"],peak:46,collab:["Taylor Swift","Shellback"]},
{t:"22 (Taylor's Version)",a:"Taylor Swift",y:2021,alb:"Red (Taylor's Version)",role:["Writer","Producer"],peak:52,collab:["Taylor Swift","Shellback"]},
{t:"We Are Never Ever Getting Back Together (Taylor's Version)",a:"Taylor Swift",y:2021,alb:"Red (Taylor's Version)",role:["Writer","Producer"],peak:55,collab:["Taylor Swift","Shellback"]},
{t:"Message in a Bottle (Taylor's Version)",a:"Taylor Swift",y:2021,alb:"Red (Taylor's Version)",role:["Writer","Producer"],peak:45,collab:["Taylor Swift","Shellback"]},
{t:"Girls Girls Girls",a:"FLETCHER",y:2021,alb:"non-album single",role:["Writer"],collab:["Cathy Dennis","FLETCHER","Dr. Luke","Jonas W. Karlsson","Kito","Madison Love","Katy Perry","Mary Weitz"]},
{t:"Can I Get It",a:"Adele",y:2021,alb:"30",role:["Writer","Producer"],collab:["Adele","Shellback"]},
// ---- 2022 ----
{t:"Gasoline",a:"The Weeknd",y:2022,alb:"Dawn FM",role:["Writer","Producer"],peak:29,collab:["Oscar Holter"]},
{t:"How Do I Make You Love Me?",a:"The Weeknd",y:2022,alb:"Dawn FM",role:["Writer"],peak:39,collab:["Oneohtrix Point Never","Axwell","Oscar Holter","Sebastian Ingrosso","Steve Angello","Matt Cohn"]},
{t:"Take My Breath",a:"The Weeknd",y:2022,alb:"Dawn FM",role:["Writer","Producer"],peak:6,collab:["Oscar Holter","Belly"]},
{t:"Sacrifice",a:"The Weeknd",y:2022,alb:"Dawn FM",role:["Writer"],peak:11,collab:["Axwell","Carl Nordström","Kevin McCord","Oscar Holter","Sebastian Ingrosso","Steve Angello"]},
{t:"Out of Time",a:"The Weeknd",y:2022,alb:"Dawn FM",role:["Writer","Producer"],peak:32,collab:["Oscar Holter"]},
{t:"Don't Break My Heart",a:"The Weeknd",y:2022,alb:"Dawn FM",role:["Writer"],collab:["Oneohtrix Point Never","Oscar Holter","Matt Cohn"]},
{t:"Is There Someone Else?",a:"The Weeknd",y:2022,alb:"Dawn FM",role:["Writer","Producer"],peak:31,collab:["Oscar Holter"]},
{t:"Less than Zero",a:"The Weeknd",y:2022,alb:"Dawn FM",role:["Writer","Producer"],peak:53,collab:["Oscar Holter"]},
{t:"Phantom Regret by Jim",a:"The Weeknd feat. Jim Carrey",y:2022,alb:"Dawn FM",role:["Writer"],collab:["Jim Carrey","Oneohtrix Point Never","Oscar Holter","Matt Cohn"]},
{t:"Supermodel",a:"Måneskin",y:2022,alb:"Rush!",role:["Writer"],collab:["Damiano David","Victoria De Angelis","Thomas Raggi","Ethan Torchio","Justin Tranter","Rami Yacoub"]},
{t:"i miss you (skin to skin)",a:"Dylan Conrique",y:2022,alb:"non-album single",role:["Writer"],collab:["Carolina Liar","Dylan Conrique","Mozella"]},
{t:"Special",a:"Lizzo",y:2022,alb:"Special",role:["Writer"],peak:52,collab:["Lizzo","Ian Kirkpatrick","R. City","Pop Wansel"]},
{t:"Grrrls",a:"Lizzo",y:2022,alb:"Special",role:["Writer"],collab:["Ad-Rock","Lizzo","Benny Blanco","Rick Rubin","Ilya Salmanzadeh","Blake Slatkin","R. City","Pop Wansel"]},
{t:"2 Be Loved (Am I Ready)",a:"Lizzo",y:2022,alb:"Special",role:["Writer"],peak:55,collab:["Lizzo","Savan Kotecha","Ilya Salmanzadeh","Peter Svensson"]},
{t:"Red Lights",a:"Max Martin",y:2022,alb:"StemDrop promo release",role:["Artist","Writer","Producer"],collab:["Savan Kotecha","Ali Payami"],trivia:"A rare release credited to 'Max Martin' as the performing artist himself, put out to launch StemDrop — a TikTok remix platform backed by Simon Cowell's Syco, Universal Music, Republic Records, and Samsung — rather than as a conventional single.",source:"https://www.musicradar.com/news/simon-cowell-max-martin-tiktok-stemdrop"},
{t:"Never Gonna Not Dance Again",a:"Pink",y:2022,alb:"Trustfall",role:["Writer"],collab:["Shellback"]},
{t:"If Jesus Was a Rockstar",a:"Kim Petras",y:2022,alb:"non-album single",role:["Writer"],collab:["Omer Fedi","Savan Kotecha","Kim Petras","Ilya Salmanzadeh","Peter Svensson"]},
// ---- 2023 ----
{t:"Radio",a:"Sigala w/ MNEK",y:2023,alb:"Every Cloud - Silver Linings",role:["Writer"],collab:["Sigala","Steven Manovski","Joakim Jarl","MNEK"]},
{t:"Baby Said",a:"Måneskin",y:2023,alb:"Rush!",role:["Writer"],collab:["Damiano David","Victoria De Angelis","Thomas Raggi","Ethan Torchio","Justin Tranter","Rami Yacoub"]},
{t:"Don't Wanna Sleep",a:"Måneskin",y:2023,alb:"Rush!",role:["Writer"],collab:["Damiano David","Victoria De Angelis","Thomas Raggi","Ethan Torchio","Justin Tranter","Rami Yacoub"]},
{t:"If Not for You",a:"Måneskin",y:2023,alb:"Rush!",role:["Writer"],collab:["Damiano David","Victoria De Angelis","Savan Kotecha","Thomas Raggi","Ethan Torchio","Justin Tranter","Rami Yacoub"]},
{t:"Eyes Closed",a:"Ed Sheeran",y:2023,alb:"non-album single",role:["Writer"],collab:["Fred again..","Shellback","Ed Sheeran"]},
{t:"Leave Me Slowly",a:"Lewis Capaldi",y:2023,alb:"Broken by Desire to Be Heavenly Sent",role:["Writer"],collab:["Lewis Capaldi","Fat Max Gsus","Oscar Holter","Savan Kotecha"]},
{t:"Thousand Pieces",a:"Kim Petras",y:2023,alb:"Feed the Beast",role:["Writer"],collab:["Dr. Luke","Fat Max Gsus","Anne Linnet","Kim Petras"]},
{t:"A Beautiful Game",a:"Ed Sheeran",y:2023,alb:"non-album single",role:["Writer"],collab:["Oscar Görres","Ed Sheeran","Foy Vance"]},
{t:"Sign Me Up",a:"Post Malone",y:2023,alb:"Austin",role:["Writer"],collab:["Louis Bell","Post Malone","Billy Walsh","Rami Yacoub"]},
{t:"Enough Is Enough",a:"Post Malone",y:2023,alb:"Austin",role:["Writer"],collab:["Louis Bell","Post Malone","Billy Walsh","Rami Yacoub"]},
{t:"Blank Space (Taylor's Version)",a:"Taylor Swift",y:2023,alb:"1989 (Taylor's Version)",role:["Writer","Producer"],peak:12,collab:["Shellback"]},
{t:"Style (Taylor's Version)",a:"Taylor Swift",y:2023,alb:"1989 (Taylor's Version)",role:["Writer","Producer"],peak:9,collab:["Shellback","Ali Payami"]},
{t:"All You Had to Do Was Stay (Taylor's Version)",a:"Taylor Swift",y:2023,alb:"1989 (Taylor's Version)",role:["Writer","Producer"],peak:20,collab:[]},
{t:"Shake It Off (Taylor's Version)",a:"Taylor Swift",y:2023,alb:"1989 (Taylor's Version)",role:["Writer","Producer"],peak:28,collab:["Shellback"]},
{t:"Bad Blood (Taylor's Version)",a:"Taylor Swift",y:2023,alb:"1989 (Taylor's Version)",role:["Writer","Producer"],peak:7,collab:["Shellback"]},
{t:"How You Get the Girl (Taylor's Version)",a:"Taylor Swift",y:2023,alb:"1989 (Taylor's Version)",role:["Writer","Producer"],peak:40,collab:["Shellback"]},
{t:"Wonderland (Taylor's Version)",a:"Taylor Swift",y:2023,alb:"1989 (Taylor's Version)",role:["Writer","Producer"],peak:39,collab:["Shellback"]},
{t:"New Romantics (Taylor's Version)",a:"Taylor Swift",y:2023,alb:"1989 (Taylor's Version)",role:["Writer","Producer"],peak:29,collab:["Shellback"]},
{t:"Bad Blood (Taylor's Version) (remix)",a:"Taylor Swift feat. Kendrick Lamar",y:2023,alb:"1989 (Taylor's Version)",role:["Writer","Producer"],collab:["Shellback","Kendrick Lamar"]},
{t:"Never Ending Song",a:"Conan Gray",y:2024,alb:"Found Heaven",role:["Writer"],collab:["Ilya Salmanzadeh"]},
{t:"Killing Me",a:"Conan Gray",y:2024,alb:"Found Heaven",role:["Writer"],collab:["Oscar Holter"]},
{t:"Lonely Dancers",a:"Conan Gray",y:2024,alb:"Found Heaven",role:["Writer"],collab:["Oscar Holter","Ilya Salmanzadeh"]},
{t:"Fainted Love",a:"Conan Gray",y:2024,alb:"Found Heaven",role:["Writer","Producer"],collab:[]},
{t:"The Final Fight",a:"Conan Gray",y:2024,alb:"Found Heaven",role:["Writer"],collab:["Oscar Holter","Ilya Salmanzadeh"]},
{t:"Miss You",a:"Conan Gray",y:2024,alb:"Found Heaven",role:["Writer"],collab:["Oscar Holter"]},
{t:"Boys & Girls",a:"Conan Gray",y:2024,alb:"Found Heaven",role:["Writer"],collab:["Oscar Holter"]},
{t:"BroZone's Back",a:"Anna Kendrick, Justin Timberlake, Daveed Diggs, Eric André",y:2023,alb:"Trolls Band Together soundtrack",role:["Writer"],collab:["Dallas Austin","Michael Bivins","Barry, Robin & Maurice Gibb (Bee Gees)","Larry Curtis Johnson","Michael Edwin Johnson","Nathan Morris","Shawn Stockman","Denniz PoP"],trivia:"A medley for Trolls Band Together that interpolates several classics, including — fittingly — Max Martin & Denniz PoP's own 'Everybody (Backstreet's Back).' That's why this 2023 credit still carries a co-write with his late mentor, who died in 1998.",source:"https://www.whosampled.com/sample/1105115/Justin-Timberlake-Eric-Andre-Daveed-Diggs-Anna-Kendrick-BroZone's-Back-Backstreet-Boys-Everybody-(Backstreet's-Back)/"},
// ---- 2024 ----
{t:"Yes, And?",a:"Ariana Grande",y:2024,alb:"Eternal Sunshine",role:["Writer"],peak:1,collab:["Ilya Salmanzadeh"]},
{t:"Bye",a:"Ariana Grande",y:2024,alb:"Eternal Sunshine",role:["Writer"],peak:25,collab:["Ilya Salmanzadeh"]},
{t:"Don't Wanna Break Up Again",a:"Ariana Grande",y:2024,alb:"Eternal Sunshine",role:["Writer"],peak:28,collab:["Ilya Salmanzadeh"]},
{t:"Saturn Returns Interlude",a:"Ariana Grande",y:2024,alb:"Eternal Sunshine",role:["Writer"],collab:["Diana Garland","Ilya Salmanzadeh"]},
{t:"Eternal Sunshine",a:"Ariana Grande",y:2024,alb:"Eternal Sunshine",role:["Writer"],peak:23,collab:["David Park","Shintaro Yasuda"]},
{t:"Supernatural",a:"Ariana Grande",y:2024,alb:"Eternal Sunshine",role:["Writer"],peak:17,collab:["Oscar Görres"]},
{t:"True Story",a:"Ariana Grande",y:2024,alb:"Eternal Sunshine",role:["Writer","Producer"],peak:30,collab:[]},
{t:"The Boy Is Mine",a:"Ariana Grande",y:2024,alb:"Eternal Sunshine",role:["Writer"],peak:16,collab:["David Park","Shintaro Yasuda"]},
{t:"We Can't Be Friends (Wait for Your Love)",a:"Ariana Grande",y:2024,alb:"Eternal Sunshine",role:["Writer"],peak:1,collab:["Ilya Salmanzadeh"]},
{t:"Imperfect for You",a:"Ariana Grande",y:2024,alb:"Eternal Sunshine",role:["Writer"],peak:37,collab:["Peter Karl Wilhelm Kahm","Ilya Salmanzadeh"]},
{t:"Supernatural (Remix)",a:"Ariana Grande w/ Troye Sivan",y:2024,alb:"Eternal Sunshine (Slightly Deluxe)",role:["Writer"],collab:["Oscar Görres","Leland","Troye Sivan"]},
{t:"Yes, And? (Remix)",a:"Ariana Grande w/ Mariah Carey",y:2024,alb:"Eternal Sunshine (Slightly Deluxe)",role:["Writer"],collab:["Ilya Salmanzadeh"]},
{t:"Drive Over Me",a:"Between Friends",y:2024,alb:"garage sale",role:["Writer"],collab:["Brandon Hudson","Savannah Hudson","Luka Kloser"]},
{t:"Everything but You",a:"Bonnie McKee",y:2024,alb:"Hot City",role:["Writer"],collab:["Joakim Åhlund","Bonnie McKee","Johnnie Newman"]},
{t:"feelslikeimfallinginlove",a:"Coldplay",y:2024,alb:"Moon Music",role:["Writer"],peak:81,collab:["Coldplay","Apple Martin","Jon Hopkins","Tim Rutili"]},
{t:"We Pray",a:"Coldplay feat. Little Simz, Burna Boy, Elyanna & Tini",y:2024,alb:"Moon Music",role:["Writer"],collab:["Coldplay","Ilya Salmanzadeh","Jay-Z","Little Simz","Burna Boy","Elyanna","Tini"]},
{t:"Jupiter",a:"Coldplay",y:2024,alb:"Moon Music",role:["Writer"],collab:["Coldplay","Moses Martin","Livvi Franc","Jacob Collier","Ilya Salmanzadeh","Orlando le Fleming"]},
{t:"IAAM",a:"Coldplay",y:2024,alb:"Moon Music",role:["Writer"],collab:["Oscar Holter"]},
{t:"Lithonia",a:"Childish Gambino",y:2024,alb:"Bando Stone & the New World",role:["Writer"],collab:["Ludwig Göransson","Riley Stephen Mackin","Michael Uzowuru"]},
{t:"A Place Where Love Goes",a:"Childish Gambino",y:2024,alb:"Bando Stone & the New World",role:["Writer"],collab:["Ludwig Göransson","Oscar Holter","DJ Dahi"]},
{t:"New Woman",a:"Lisa feat. Rosalía",y:2024,alb:"Alter Ego",role:["Writer"],collab:["Rosalía","Ilya Salmanzadeh","Tove Burman","Tove Lo"]},
{t:"Dancing in the Flames",a:"The Weeknd",y:2024,alb:"non-album single",role:["Writer","Producer"],peak:14,collab:["Oscar Holter"]},
// ---- 2025 ----
{t:"Open Hearts",a:"The Weeknd",y:2025,alb:"Hurry Up Tomorrow",role:["Writer","Producer"],peak:48,collab:["Oscar Holter"]},
{t:"Give Me Mercy",a:"The Weeknd",y:2025,alb:"Hurry Up Tomorrow",role:["Writer","Producer"],collab:["Oscar Holter"]},
{t:"Runaway",a:"The Weeknd",y:2025,alb:"Hurry Up Tomorrow (First Pressing)",role:["Writer"],collab:["Oscar Holter","Ilya Salmanzadeh"]},
{t:"Society",a:"The Weeknd",y:2025,alb:"Hurry Up Tomorrow (First Pressing)",role:["Writer","Producer"],collab:["Oscar Holter"]},
{t:"¿Es En Serio?",a:"Ela Taubert",y:2025,alb:"non-album single",role:["Writer"],collab:["Kevin Augusto Aguirre Buitrago","Pio Felipe Perilla Cleves","Ela Taubert","Rami Yacoub"]},
{t:"American Bitch",a:"Between Friends",y:2025,alb:"Wow!",role:["Writer"],collab:["Brandon Hudson","Savannah Hudson"]},
{t:"XD",a:"Between Friends",y:2025,alb:"Wow!",role:["Writer"],collab:["Brandon Hudson","Eden","Savannah Hudson"]},
{t:"The Fate of Ophelia",a:"Taylor Swift",y:2025,alb:"The Life of a Showgirl",role:["Writer","Producer"],peak:1,collab:["Shellback"]},
{t:"Elizabeth Taylor",a:"Taylor Swift",y:2025,alb:"The Life of a Showgirl",role:["Writer","Producer"],peak:3,collab:["Shellback"]},
{t:"Opalite",a:"Taylor Swift",y:2025,alb:"The Life of a Showgirl",role:["Writer","Producer"],peak:1,collab:["Shellback"]},
{t:"Father Figure",a:"Taylor Swift",y:2025,alb:"The Life of a Showgirl",role:["Writer","Producer"],peak:4,collab:["Shellback","George Michael"]},
{t:"Eldest Daughter",a:"Taylor Swift",y:2025,alb:"The Life of a Showgirl",role:["Writer","Producer"],peak:9,collab:["Shellback"]},
{t:"Ruin the Friendship",a:"Taylor Swift",y:2025,alb:"The Life of a Showgirl",role:["Writer","Producer"],peak:11,collab:["Shellback"]},
{t:"Actually Romantic",a:"Taylor Swift",y:2025,alb:"The Life of a Showgirl",role:["Writer","Producer"],peak:7,collab:["Shellback"]},
{t:"Wi$h Li$t",a:"Taylor Swift",y:2025,alb:"The Life of a Showgirl",role:["Writer","Producer"],peak:6,collab:["Shellback"]},
{t:"Wood",a:"Taylor Swift",y:2025,alb:"The Life of a Showgirl",role:["Writer","Producer"],peak:5,collab:["Shellback"]},
{t:"CANCELLED!",a:"Taylor Swift",y:2025,alb:"The Life of a Showgirl",role:["Writer","Producer"],peak:10,collab:["Shellback"]},
{t:"Honey",a:"Taylor Swift",y:2025,alb:"The Life of a Showgirl",role:["Writer","Producer"],peak:12,collab:["Shellback"]},
{t:"The Life of a Showgirl",a:"Taylor Swift feat. Sabrina Carpenter",y:2025,alb:"The Life of a Showgirl",role:["Writer","Producer"],collab:["Shellback","Sabrina Carpenter"],trivia:"Marked Max Martin & Shellback producing every track on a Taylor Swift album for the first time since 2017's Reputation.",source:"https://en.wikipedia.org/wiki/The_Life_of_a_Showgirl"},
{t:"I Want You",a:"Debbii Dawson",y:2025,alb:"non-album single",role:["Writer"],collab:["Debbii Dawson","Elvira Anderfjärd","Luka Kloser","Rami Yacoub"]},
// ---- 2026 ----
{t:"Talk to Me",a:"Robyn",y:2026,alb:"Sexistential",role:["Writer"],collab:["Klas Åhlund","Oscar Holter","Robyn"]},
{t:"Into the Sun",a:"Robyn",y:2026,alb:"Sexistential",role:["Writer"],collab:["Klas Åhlund","Oscar Holter","Robyn"]},
{t:"One Foot in the Grave",a:"Kenny Whitmire",y:2026,alb:"Fool In a King Sized Bed",role:["Writer"],collab:["Thomas Mirels"]},
{t:"Hate That I Made You Love Me",a:"Ariana Grande",y:2026,alb:"Petal",role:["Writer"],peak:1,collab:["Ilya Salmanzadeh"]},
{t:"Petal",a:"Ariana Grande",y:2026,alb:"Petal",role:["Writer"],peak:4,collab:["Ilya Salmanzadeh"]},
{t:"Stay",a:"Ariana Grande",y:2026,alb:"Petal",role:["Writer"],peak:22,collab:["Ilya Salmanzadeh"]},
{t:"Happiness Is So Sad",a:"Swedish House Mafia w/ Lykke Li",y:2026,alb:"non-album single",role:["Writer"],collab:["Axwell","Sebastian Ingrosso","Steve Angello","Fred again..","Lykke Li","Oscar Holter","Yaroslav Polikarpov"]},
];

const MAX_MARTIN_TRIVIA = [
{text:"His real name is Karl Martin Sandberg — 'Max Martin' was actually a nickname invented by E-Type and mentor Denniz PoP without his knowledge. He only found out when the printed records arrived with the new name on them.",source:"https://en.wikipedia.org/wiki/Max_Martin"},
{text:"He was born February 26, 1971, in Stenhamra, a suburb of Stockholm, Sweden, to a police-officer father and a middle-school-teacher mother.",source:"https://en.wikipedia.org/wiki/Max_Martin"},
{text:"Before pop stardom, he was the singer/frontman of the glam-metal band It's Alive, formed in Stockholm in 1987, performing under the stage name 'Martin White.' Their one album, Earthquake Visions (1993), sold only around 30,000 copies before he left the band in 1995 to focus on production.",source:"https://en.wikipedia.org/wiki/It%27s_Alive_(band)"},
{text:"He credits Sweden's free public music education program directly for his career, saying he has 'public music education to thank for everything.'",source:"https://en.wikipedia.org/wiki/Max_Martin"},
{text:"Denniz PoP (Dag Volle) spotted his songwriting talent and mentored him at Cheiron Studios in Stockholm starting in 1993 — Cheiron became the pop hit factory behind Backstreet Boys, *NSYNC, and Britney Spears.",source:"https://en.wikipedia.org/wiki/Max_Martin"},
{text:"Cheiron Studios closed in 2000 after Denniz PoP died of cancer at just 35; Martin later founded his own production house, Maratone, in January 2001.",source:"https://en.wikipedia.org/wiki/Max_Martin"},
{text:"'...Baby One More Time' was originally written and pitched to TLC, who turned it down as too bubblegum/too Swedish. Britney Spears recorded it instead, and it became one of the best-selling singles ever.",source:"https://en.wikipedia.org/wiki/...Baby_One_More_Time"},
{text:"He has 30 Billboard Hot 100 #1 singles as a writer/co-writer — second only to Paul McCartney (32) among all songwriters, and he passed John Lennon's 26 #1s in March 2024.",source:"https://en.wikipedia.org/wiki/Max_Martin"},
{text:"He's won the ASCAP Pop Songwriter of the Year award more times than anyone else — 11 times — and in 1999 became the first non-American ever to win it.",source:"https://en.wikipedia.org/wiki/Max_Martin"},
{text:"He's won 5 Grammy Awards, including Producer of the Year, and received two Academy Award nominations for Best Original Song ('Can't Stop the Feeling!' with Justin Timberlake, and later work).",source:"https://en.wikipedia.org/wiki/Max_Martin"},
{text:"He received Sweden's Polar Music Prize, one of the country's highest honors in music, often called 'the Nobel Prize of music.'",source:"https://www.polarmusicprize.org/laureates/max-martin/"},
{text:"His songwriting method is often called 'melodic math': he prioritizes the melody and phonetic feel of a lyric over its literal meaning, which is why some of his biggest hits (like 'I Want It That Way') have lyrics that don't fully make logical sense.",source:"https://en.wikipedia.org/wiki/Max_Martin"},
{text:"At Cheiron and beyond, he flipped the usual studio order — the instrumental track and melody were often fully written and produced before the artist ever stepped into the booth to record vocals.",source:"https://en.wikipedia.org/wiki/Max_Martin"},
{text:"He's famously private and rarely gives interviews or appears on camera, despite being one of the most commercially successful songwriter-producers in music history.",source:"https://en.wikipedia.org/wiki/Max_Martin"},
{text:"His mentees and collaborators — Dr. Luke, Shellback (Karl Johan Schuster), Savan Kotecha, Ilya Salmanzadeh, Ali Payami, and Oscar Holter — went on to become some of the biggest hitmakers in pop themselves, extending what's often called the 'Cheiron' or 'Stockholm' sound.",source:"https://en.wikipedia.org/wiki/Max_Martin"},
{text:"'If U Seek Amy' (Britney Spears, 2008) hid a phonetic double-entendre in its title/chorus that caused radio and parental-advocacy controversy.",source:"https://en.wikipedia.org/wiki/If_U_Seek_Amy"},
{text:"'Can't Feel My Face' (The Weeknd, 2015) is, on its surface, a euphoric disco-pop love song — but it's actually about the numbing rush of cocaine use.",source:"https://en.wikipedia.org/wiki/Can%27t_Feel_My_Face"},
{text:"'Blinding Lights' (The Weeknd, 2020) was named the greatest Billboard Hot 100 song of all time in Billboard's 2021 60th-anniversary retrospective and set the record for most weeks on the Hot 100.",source:"https://en.wikipedia.org/wiki/Blinding_Lights"},
{text:"He co-wrote nearly the entire Taylor Swift album 1989 (2014) and later re-recorded almost all of those songs again for 1989 (Taylor's Version) in 2023.",source:"https://en.wikipedia.org/wiki/1989_(Taylor_Swift_album)"},
{text:"& Juliet, a jukebox musical built around dozens of songs Max Martin wrote or co-wrote, debuted in London's West End in 2019 and later moved to Broadway.",source:"https://en.wikipedia.org/wiki/%26_Juliet"},
{text:"He occasionally releases music as a performing artist himself under the name 'Max Martin' — including 'Red Lights' (2022), put out to launch StemDrop, a TikTok remix platform backed by Simon Cowell's Syco, Universal Music, Republic Records, and Samsung.",source:"https://www.musicradar.com/news/simon-cowell-max-martin-tiktok-stemdrop"},
{text:"He splits his time between Los Angeles and Stockholm, and still records at Maratone/MXM studios in both cities.",source:"https://en.wikipedia.org/wiki/Max_Martin"},
{text:"'Roar' (Katy Perry, 2013) faced public comparisons to Sara Bareilles' 'Brave,' released just months earlier — both songs share a similar chord/melodic feel, though neither camp pursued legal action.",source:"https://en.wikipedia.org/wiki/Roar_(song)"},
];
